#ifndef GUARD_FIELD_EFFECT_CONSTANTS_H
#define GUARD_FIELD_EFFECT_CONSTANTS_H

#define FLDEFF_EXCLAMATION_MARK_ICON     0 
#define FLDEFF_USE_CUT_ON_GRASS          1
#define FLDEFF_USE_CUT_ON_TREE           2
#define FLDEFF_SHADOW                    3
#define FLDEFF_TALL_GRASS                4
#define FLDEFF_RIPPLE                    5
#define FLDEFF_FIELD_MOVE_SHOW_MON       6
#define FLDEFF_ASH                       7
#define FLDEFF_SURF_BLOB                 8
#define FLDEFF_USE_SURF                  9
#define FLDEFF_DUST                      10
#define FLDEFF_USE_SECRET_POWER_CAVE     11
#define FLDEFF_JUMP_TALL_GRASS           12
#define FLDEFF_SAND_FOOTPRINTS           13
#define FLDEFF_JUMP_BIG_SPLASH           14
#define FLDEFF_SPLASH                    15
#define FLDEFF_JUMP_SMALL_SPLASH         16
#define FLDEFF_LONG_GRASS                17
#define FLDEFF_JUMP_LONG_GRASS           18
#define FLDEFF_WATER_SURFACING           19
#define FLDEFF_BERRY_TREE_GROWTH_SPARKLE 20
#define FLDEFF_DEEP_SAND_FOOTPRINTS      21
#define FLDEFF_POKECENTER_HEAL           22
#define FLDEFF_USE_SECRET_POWER_TREE     23
#define FLDEFF_USE_SECRET_POWER_SHRUB    24
#define FLDEFF_TREE_DISGUISE             25
#define FLDEFF_MOUNTAIN_DISGUISE         26
#define FLDEFF_NPCFLY_OUT                27
#define FLDEFF_USE_FLY                   28
#define FLDEFF_FLY_IN                    29
#define FLDEFF_QUESTION_MARK_ICON        30
#define FLDEFF_FEET_IN_FLOWING_WATER     31
#define FLDEFF_BIKE_TIRE_TRACKS          32
#define FLDEFF_SAND_DISGUISE             33
#define FLDEFF_USE_ROCK_SMASH            34
#define FLDEFF_USE_DIG                   35
#define FLDEFF_SAND_PILE                 36
#define FLDEFF_USE_STRENGTH              37
#define FLDEFF_SHORT_GRASS               38
#define FLDEFF_HOT_SPRINGS_WATER         39
#define FLDEFF_USE_WATERFALL             40
#define FLDEFF_USE_DIVE                  41
#define FLDEFF_POKEBALL                  42
#define FLDEFF_HEART_ICON                43
#define FLDEFF_NOP_47                    44
#define FLDEFF_NOP_48                    45
#define FLDEFF_ASH_PUFF                  46
#define FLDEFF_ASH_LAUNCH                47
#define FLDEFF_SWEET_SCENT               48
#define FLDEFF_SAND_PILLAR               49
#define FLDEFF_BUBBLES                   50
#define FLDEFF_SPARKLE                   51
#define FLDEFF_SECRET_POWER_CAVE         52
#define FLDEFF_SECRET_POWER_TREE         53
#define FLDEFF_SECRET_POWER_SHRUB        54
#define FLDEFF_CUT_GRASS                 55
#define FLDEFF_FIELD_MOVE_SHOW_MON_INIT  56
#define FLDEFF_USE_TOMB_PUZZLE_EFFECT    57
#define FLDEFF_PCTURN_ON                 58
#define FLDEFF_HALL_OF_FAME_RECORD       59
#define FLDEFF_USE_TELEPORT              60
#define FLDEFF_RAYQUAZA_SPOTLIGHT        61
#define FLDEFF_DESTROY_DEOXYS_ROCK       62
#define FLDEFF_MOVE_DEOXYS_ROCK          63

#define FLDEFFOBJ_SHADOW_S              0
#define FLDEFFOBJ_SHADOW_M              1
#define FLDEFFOBJ_SHADOW_L              2
#define FLDEFFOBJ_SHADOW_XL             3
#define FLDEFFOBJ_TALL_GRASS            4
#define FLDEFFOBJ_RIPPLE                5
#define FLDEFFOBJ_ASH                   6
#define FLDEFFOBJ_SURF_BLOB             7
#define FLDEFFOBJ_ARROW                 8
#define FLDEFFOBJ_GROUND_IMPACT_DUST    9
#define FLDEFFOBJ_JUMP_TALL_GRASS       10
#define FLDEFFOBJ_SAND_FOOTPRINTS       11
#define FLDEFFOBJ_JUMP_BIG_SPLASH       12
#define FLDEFFOBJ_SPLASH                13
#define FLDEFFOBJ_JUMP_SMALL_SPLASH     14
#define FLDEFFOBJ_LONG_GRASS            15
#define FLDEFFOBJ_JUMP_LONG_GRASS       16
#define FLDEFFOBJ_WATER_SURFACING       17
#define FLDEFFOBJ_REFLECTION_DISTORTION 18
#define FLDEFFOBJ_SPARKLE               19
#define FLDEFFOBJ_DEEP_SAND_FOOTPRINTS  20
#define FLDEFFOBJ_TREE_DISGUISE         21
#define FLDEFFOBJ_MOUNTAIN_DISGUISE     22
#define FLDEFFOBJ_BIRD                  23
#define FLDEFFOBJ_BIKE_TIRE_TRACKS      24
#define FLDEFFOBJ_SAND_DISGUISE         25
#define FLDEFFOBJ_SAND_PILE             26
#define FLDEFFOBJ_SHORT_GRASS           27
#define FLDEFFOBJ_HOT_SPRINGS_WATER     28
#define FLDEFFOBJ_ASH_PUFF              29
#define FLDEFFOBJ_ASH_LAUNCH            30
#define FLDEFFOBJ_BUBBLES               31
#define FLDEFFOBJ_SMALL_SPARKLE         32
#define FLDEFFOBJ_RAYQUAZA              33

#define FLDEFF_PAL_TAG_CUT_GRASS          0x1000
#define FLDEFF_PAL_TAG_SECRET_POWER_TREE  0x1003
#define FLDEFF_PAL_TAG_GENERAL_0          0x1004
#define FLDEFF_PAL_TAG_GENERAL_1          0x1005
#define FLDEFF_PAL_TAG_POKEBALL_GLOW      0x1007
#define FLDEFF_PAL_TAG_SECRET_POWER_PLANT 0x1008
#define FLDEFF_PAL_TAG_POKEBALL           0x1009
#define FLDEFF_PAL_TAG_ASH                0x100D
#define FLDEFF_PAL_TAG_SAND_PILLAR        0x100E
#define FLDEFF_PAL_TAG_SMALL_SPARKLE      0x100F
#define FLDEFF_PAL_TAG_HOF_MONITOR        0x1010
#define FLDEFF_PAL_TAG_UNKNOWN            0x1011

#endif // GUARD_FIELD_EFFECT_CONSTANTS_H
