#ifndef GUARD_CONSTANTS_SONGS_H
#define GUARD_CONSTANTS_SONGS_H

// Original JP names listed on right, along with any additional notes

#define MUS_DUMMY                   0 // MUS_DUMMY
#define SE_USE_ITEM                 1 // SE_KAIFUKU
#define SE_PC_LOGIN                 2 // SE_PC_LOGIN
#define SE_PC_OFF                   3 // SE_PC_OFF
#define SE_PC_ON                    4 // SE_PC_ON
#define SE_SELECT                   5 // SE_SELECT
#define SE_WIN_OPEN                 6 // SE_WIN_OPEN
#define SE_WALL_HIT                 7 // SE_WALL_HIT
#define SE_DOOR                     8 // SE_DOOR
#define SE_EXIT                     9 // SE_KAIDAN
#define SE_LEDGE                    10 // SE_DANSA
#define SE_BIKE_BELL                11 // SE_JITENSYA
#define SE_NOT_EFFECTIVE            12 // SE_KOUKA_L
#define SE_EFFECTIVE                13 // SE_KOUKA_M
#define SE_SUPER_EFFECTIVE          14 // SE_KOUKA_H
#define SE_BALL_OPEN                15 // SE_BOWA2
#define SE_FAINT                    16 // SE_POKE_DEAD
#define SE_FLEE                     17 // SE_NIGERU
#define SE_SLIDING_DOOR             18 // SE_JIDO_DOA
#define SE_SHIP                     19 // SE_NAMINORI
#define SE_BANG                     20 // SE_BAN
#define SE_PIN                      21 // SE_PIN (General "good", commonly for "!")
#define SE_BOO                      22 // SE_BOO (General "bad")
#define SE_BALL                     23 // SE_BOWA (Giving Poké Ball to nurse, Poké Ball shake, etc)
#define SE_CONTEST_PLACE            24 // SE_JYUNI
#define SE_SUCCESS                  25 // SE_SEIKAI
#define SE_FAILURE                  26 // SE_HAZURE
#define SE_EXP                      27 // SE_EXP
#define SE_BIKE_HOP                 28 // SE_JITE_PYOKO
#define SE_SWITCH                   29 // SE_MU_PACHI
#define SE_CLICK                    30 // SE_TK_KASYA
#define SE_FU_ZAKU                  31 // SE_FU_ZAKU (Unknown purpose, unused)
#define SE_CONTEST_CONDITION_LOSE   32 // SE_FU_ZAKU2
#define SE_LAVARIDGE_FALL_WARP      33 // SE_FU_ZUZUZU
#define SE_ICE_STAIRS               34 // SE_RU_GASHIN
#define SE_ICE_BREAK                35 // SE_RU_GASYAN
#define SE_ICE_CRACK                36 // SE_RU_BARI
#define SE_FALL                     37 // SE_RU_HYUU
#define SE_UNLOCK                   38 // SE_KI_GASYAN
#define SE_WARP_IN                  39 // SE_TK_WARPIN
#define SE_WARP_OUT                 40 // SE_TK_WARPOUT
#define SE_REPEL                    41 // SE_TU_SAA
#define SE_ROTATING_GATE            42 // SE_HI_TURUN
#define SE_TRUCK_MOVE               43 // SE_TRACK_MOVE
#define SE_TRUCK_STOP               44 // SE_TRACK_STOP
#define SE_TRUCK_UNLOAD             45 // SE_TRACK_HAIKI
#define SE_TRUCK_DOOR               46 // SE_TRACK_DOOR
#define SE_BERRY_BLENDER            47 // SE_MOTER
#define SE_CARD                     48 // SE_CARD (Unused, different from the RS card SE)
#define SE_SAVE                     49 // SE_SAVE
#define SE_BALL_BOUNCE_1            50 // SE_KON
#define SE_BALL_BOUNCE_2            51 // SE_KON2
#define SE_BALL_BOUNCE_3            52 // SE_KON3
#define SE_BALL_BOUNCE_4            53 // SE_KON4
#define SE_BALL_TRADE               54 // SE_SUIKOMU
#define SE_BALL_THROW               55 // SE_NAGERU
#define SE_PUDDLE                   56 // SE_MIZU
#define SE_BRIDGE_WALK              57 // SE_HASHI
#define SE_ITEMFINDER               58 // SE_DAUGI
#define SE_DING_DONG                59 // SE_PINPON
#define SE_BALLOON_RED              60 // SE_FUUSEN1
#define SE_BREAKABLE_DOOR           61 // SE_TOY_KABE
#define SE_MUD_BALL                 62 // SE_TOY_DANGO
#define SE_FIELD_POISON             63 // SE_DOKU
#define SE_ESCALATOR                64 // SE_ESUKA
#define SE_THUNDERSTORM             65 // SE_T_AME
#define SE_THUNDERSTORM_STOP        66 // SE_T_AME_E
#define SE_DOWNPOUR                 67 // SE_T_OOAME
#define SE_DOWNPOUR_STOP            68 // SE_T_OOAME_E
#define SE_RAIN                     69 // SE_T_KOAME
#define SE_RAIN_STOP                70 // SE_T_KOAME_E
#define SE_THUNDER                  71 // SE_T_KAMI
#define SE_THUNDER2                 72 // SE_T_KAMI2
#define SE_ELEVATOR                 73 // SE_ELEBETA
#define SE_LOW_HEALTH               74 // SE_HINSI
#define SE_EXP_MAX                  75 // SE_EXPMAX
#define SE_ROULETTE_BALL            76 // SE_TAMAKORO
#define SE_ROULETTE_BALL2           77 // SE_TAMAKORO_E
#define SE_TAILLOW_WING_FLAP        78 // SE_BASABASA
#define SE_SHOP                     79 // SE_REGI
#define SE_CONTEST_HEART            80 // SE_C_GAJI
#define SE_CONTEST_CURTAIN_RISE     81 // SE_C_MAKU_U
#define SE_CONTEST_CURTAIN_FALL     82 // SE_C_MAKU_D
#define SE_CONTEST_ICON_CHANGE      83 // SE_C_PASI
#define SE_CONTEST_ICON_CLEAR       84 // SE_C_SYU
#define SE_CONTEST_MONS_TURN        85 // SE_C_PIKON
#define SE_SHINY                    86 // SE_REAPOKE
#define SE_INTRO_BLAST              87 // SE_OP_BASYU
#define SE_MUGSHOT                  88 // SE_BT_START
#define SE_APPLAUSE                 89 // SE_DENDOU
#define SE_VEND                     90 // SE_JIHANKI
#define SE_ORB                      91 // SE_TAMA
#define SE_DEX_SCROLL               92 // SE_Z_SCROLL
#define SE_DEX_PAGE                 93 // SE_Z_PAGE
#define SE_POKENAV_ON               94 // SE_PN_ON
#define SE_POKENAV_OFF              95 // SE_PN_OFF
#define SE_DEX_SEARCH               96 // SE_Z_SEARCH
#define SE_EGG_HATCH                97 // SE_TAMAGO
#define SE_BALL_TRAY_ENTER          98 // SE_TB_START
#define SE_BALL_TRAY_BALL           99 // SE_TB_KON
#define SE_BALL_TRAY_EXIT           100 // SE_TB_KARA
#define SE_GLASS_FLUTE              101 // SE_BIDORO
// Move SFX
#define SE_M_THUNDERBOLT            102 // SE_W085
#define SE_M_THUNDERBOLT2           103 // SE_W085B
#define SE_M_HARDEN                 104 // SE_W231
#define SE_M_NIGHTMARE              105 // SE_W171
#define SE_M_VITAL_THROW            106 // SE_W233
#define SE_M_VITAL_THROW2           107 // SE_W233B
#define SE_M_BUBBLE                 108 // SE_W145
#define SE_M_BUBBLE2                109 // SE_W145B
#define SE_M_BUBBLE3                110 // SE_W145C
#define SE_M_RAIN_DANCE             111 // SE_W240
#define SE_M_CUT                    112 // SE_W015
#define SE_M_STRING_SHOT            113 // SE_W081
#define SE_M_STRING_SHOT2           114 // SE_W081B
#define SE_M_ROCK_THROW             115 // SE_W088
#define SE_M_GUST                   116 // SE_W016
#define SE_M_GUST2                  117 // SE_W016B
#define SE_M_DOUBLE_SLAP            118 // SE_W003
#define SE_M_DOUBLE_TEAM            119 // SE_W104
#define SE_M_RAZOR_WIND             120 // SE_W013
#define SE_M_ICY_WIND               121 // SE_W196
#define SE_M_THUNDER_WAVE           122 // SE_W086
#define SE_M_COMET_PUNCH            123 // SE_W004
#define SE_M_MEGA_KICK              124 // SE_W025
#define SE_M_MEGA_KICK2             125 // SE_W025B
#define SE_M_CRABHAMMER             126 // SE_W152
#define SE_M_JUMP_KICK              127 // SE_W026
#define SE_M_FLAME_WHEEL            128 // SE_W172
#define SE_M_FLAME_WHEEL2           129 // SE_W172B
#define SE_M_FLAMETHROWER           130 // SE_W053
#define SE_M_FIRE_PUNCH             131 // SE_W007
#define SE_M_TOXIC                  132 // SE_W092
#define SE_M_SACRED_FIRE            133 // SE_W221
#define SE_M_SACRED_FIRE2           134 // SE_W221B
#define SE_M_EMBER                  135 // SE_W052
#define SE_M_TAKE_DOWN              136 // SE_W036
#define SE_M_BLIZZARD               137 // SE_W059
#define SE_M_BLIZZARD2              138 // SE_W059B
#define SE_M_SCRATCH                139 // SE_W010
#define SE_M_VICEGRIP               140 // SE_W011
#define SE_M_WING_ATTACK            141 // SE_W017
#define SE_M_FLY                    142 // SE_W019
#define SE_M_SAND_ATTACK            143 // SE_W028
#define SE_M_RAZOR_WIND2            144 // SE_W013B
#define SE_M_BITE                   145 // SE_W044
#define SE_M_HEADBUTT               146 // SE_W029
#define SE_M_SURF                   147 // SE_W057
#define SE_M_HYDRO_PUMP             148 // SE_W056
#define SE_M_WHIRLPOOL              149 // SE_W250
#define SE_M_HORN_ATTACK            150 // SE_W030
#define SE_M_TAIL_WHIP              151 // SE_W039
#define SE_M_MIST                   152 // SE_W054
#define SE_M_POISON_POWDER          153 // SE_W077
#define SE_M_BIND                   154 // SE_W020
#define SE_M_DRAGON_RAGE            155 // SE_W082
#define SE_M_SING                   156 // SE_W047
#define SE_M_PERISH_SONG            157 // SE_W195
#define SE_M_PAY_DAY                158 // SE_W006
#define SE_M_DIG                    159 // SE_W091
#define SE_M_DIZZY_PUNCH            160 // SE_W146
#define SE_M_SELF_DESTRUCT          161 // SE_W120
#define SE_M_EXPLOSION              162 // SE_W153
#define SE_M_ABSORB_2               163 // SE_W071B
#define SE_M_ABSORB                 164 // SE_W071
#define SE_M_SCREECH                165 // SE_W103
#define SE_M_BUBBLE_BEAM            166 // SE_W062
#define SE_M_BUBBLE_BEAM2           167 // SE_W062B
#define SE_M_SUPERSONIC             168 // SE_W048
#define SE_M_BELLY_DRUM             169 // SE_W187
#define SE_M_METRONOME              170 // SE_W118
#define SE_M_BONEMERANG             171 // SE_W155
#define SE_M_LICK                   172 // SE_W122
#define SE_M_PSYBEAM                173 // SE_W060
#define SE_M_FAINT_ATTACK           174 // SE_W185
#define SE_M_SWORDS_DANCE           175 // SE_W014
#define SE_M_LEER                   176 // SE_W043
#define SE_M_SWAGGER                177 // SE_W207
#define SE_M_SWAGGER2               178 // SE_W207B
#define SE_M_HEAL_BELL              179 // SE_W215
#define SE_M_CONFUSE_RAY            180 // SE_W109
#define SE_M_SNORE                  181 // SE_W173
#define SE_M_BRICK_BREAK            182 // SE_W280
#define SE_M_GIGA_DRAIN             183 // SE_W202
#define SE_M_PSYBEAM2               184 // SE_W060B
#define SE_M_SOLAR_BEAM             185 // SE_W076
#define SE_M_PETAL_DANCE            186 // SE_W080
#define SE_M_TELEPORT               187 // SE_W100
#define SE_M_MINIMIZE               188 // SE_W107
#define SE_M_SKETCH                 189 // SE_W166
#define SE_M_SWIFT                  190 // SE_W129
#define SE_M_REFLECT                191 // SE_W115
#define SE_M_BARRIER                192 // SE_W112
#define SE_M_DETECT                 193 // SE_W197
#define SE_M_LOCK_ON                194 // SE_W199
#define SE_M_MOONLIGHT              195 // SE_W236
#define SE_M_CHARM                  196 // SE_W204
#define SE_M_CHARGE                 197 // SE_W268
#define SE_M_STRENGTH               198 // SE_W070
#define SE_M_HYPER_BEAM             199 // SE_W063
#define SE_M_WATERFALL              200 // SE_W127
#define SE_M_REVERSAL               201 // SE_W179
#define SE_M_ACID_ARMOR             202 // SE_W151
#define SE_M_SANDSTORM              203 // SE_W201
#define SE_M_TRI_ATTACK             204 // SE_W161
#define SE_M_TRI_ATTACK2            205 // SE_W161B
#define SE_M_ENCORE                 206 // SE_W227
#define SE_M_ENCORE2                207 // SE_W227B
#define SE_M_BATON_PASS             208 // SE_W226
#define SE_M_MILK_DRINK             209 // SE_W208
#define SE_M_ATTRACT                210 // SE_W213
#define SE_M_ATTRACT2               211 // SE_W213B
#define SE_M_MORNING_SUN            212 // SE_W234
#define SE_M_FLATTER                213 // SE_W260
#define SE_M_SAND_TOMB              214 // SE_W328
#define SE_M_GRASSWHISTLE           215 // SE_W320
#define SE_M_SPIT_UP                216 // SE_W255
#define SE_M_DIVE                   217 // SE_W291
#define SE_M_EARTHQUAKE             218 // SE_W089
#define SE_M_TWISTER                219 // SE_W239
#define SE_M_SWEET_SCENT            220 // SE_W230
#define SE_M_YAWN                   221 // SE_W281
#define SE_M_SKY_UPPERCUT           222 // SE_W327
#define SE_M_STAT_INCREASE          223 // SE_W287
#define SE_M_HEAT_WAVE              224 // SE_W257
#define SE_M_UPROAR                 225 // SE_W253
#define SE_M_HAIL                   226 // SE_W258
#define SE_M_COSMIC_POWER           227 // SE_W322
#define SE_M_TEETER_DANCE           228 // SE_W298
#define SE_M_STAT_DECREASE          229 // SE_W287B
#define SE_M_HAZE                   230 // SE_W114
#define SE_M_HYPER_BEAM2            231 // SE_W063B
// FRLG SFX
#define SE_RG_DOOR                  232 // SE_RG_W_DOOR
#define SE_RG_CARD_FLIP             233 // SE_RG_CARD1
#define SE_RG_CARD_FLIPPING         234 // SE_RG_CARD2
#define SE_RG_CARD_OPEN             235 // SE_RG_CARD3
#define SE_RG_BAG_CURSOR            236 // SE_RG_BAG1
#define SE_RG_BAG_POCKET            237 // SE_RG_BAG2
#define SE_RG_BALL_CLICK            238 // SE_RG_GETTING
#define SE_RG_SHOP                  239 // SE_RG_SHOP
#define SE_RG_SS_ANNE_HORN          240 // SE_RG_KITEKI
#define SE_RG_HELP_OPEN             241 // SE_RG_HELP_OP
#define SE_RG_HELP_CLOSE            242 // SE_RG_HELP_CL
#define SE_RG_HELP_ERROR            243 // SE_RG_HELP_NG
#define SE_RG_DEOXYS_MOVE           244 // SE_RG_DEOMOV
// New Emerald SFX
#define SE_POKENAV_CALL             245 // SE_TOREEYE
#define SE_POKENAV_HANG_UP          246 // SE_TOREOFF
#define SE_ARENA_TIMEUP1            247 // SE_HANTEI1
#define SE_ARENA_TIMEUP2            248 // SE_HANTEI2
#define SE_PIKE_CURTAIN_CLOSE       249 // SE_CURTAIN
#define SE_PIKE_CURTAIN_OPEN        250 // SE_CURTAIN1
#define SE_SUDOWOODO_SHAKE          251 // SE_USSOKI

// Music
#define MUS_LITTLEROOT_TEST         350 // MUS_TETSUJI
#define MUS_GSC_ROUTE38             351 // MUS_FIELD13
#define MUS_CAUGHT                  352 // MUS_KACHI22
#define MUS_VICTORY_WILD            353 // MUS_KACHI2
#define MUS_VICTORY_GYM_LEADER      354 // MUS_KACHI3
#define MUS_VICTORY_LEAGUE          355 // MUS_KACHI5
#define MUS_C_COMM_CENTER           356 // MUS_PCC
#define MUS_GSC_PEWTER              357 // MUS_NIBI
#define MUS_C_VS_LEGEND_BEAST       358 // MUS_SUIKUN
#define MUS_ROUTE101                359 // MUS_DOORO1
#define MUS_ROUTE110                360 // MUS_DOORO_X1
#define MUS_ROUTE120                361 // MUS_DOORO_X3
#define MUS_PETALBURG               362 // MUS_MACHI_S2
#define MUS_OLDALE                  363 // MUS_MACHI_S4
#define MUS_GYM                     364 // MUS_GIM
#define MUS_SURF                    365 // MUS_NAMINORI
#define MUS_PETALBURG_WOODS         366 // MUS_DAN01
#define MUS_LEVEL_UP                367 // MUS_FANFA1
#define MUS_HEAL                    368 // MUS_ME_ASA
#define MUS_OBTAIN_BADGE            369 // MUS_ME_BACHI
#define MUS_OBTAIN_ITEM             370 // MUS_FANFA4
#define MUS_EVOLVED                 371 // MUS_FANFA5
#define MUS_OBTAIN_TMHM             372 // MUS_ME_WAZA
#define MUS_LILYCOVE_MUSEUM         373 // MUS_BIJYUTU
#define MUS_ROUTE122                374 // MUS_DOORO_X4
#define MUS_OCEANIC_MUSEUM          375 // MUS_FUNE_KAN
#define MUS_EVOLUTION_INTRO         376 // MUS_ME_SHINKA
#define MUS_EVOLUTION               377 // MUS_SHINKA
#define MUS_MOVE_DELETED            378 // MUS_ME_WASURE
#define MUS_ENCOUNTER_GIRL          379 // MUS_SYOUJOEYE
#define MUS_ENCOUNTER_MALE          380 // MUS_BOYEYE
#define MUS_ABANDONED_SHIP          381 // MUS_DAN02
#define MUS_FORTREE                 382 // MUS_MACHI_S3
#define MUS_BIRCH_LAB               383 // MUS_ODAMAKI
#define MUS_B_TOWER_RS              384 // MUS_B_TOWER
#define MUS_ENCOUNTER_SWIMMER       385 // MUS_SWIMEYE
#define MUS_CAVE_OF_ORIGIN          386 // MUS_DAN03
#define MUS_OBTAIN_BERRY            387 // MUS_ME_KINOMI
#define MUS_AWAKEN_LEGEND           388 // MUS_ME_TAMA
#define MUS_SLOTS_JACKPOT           389 // MUS_ME_B_BIG
#define MUS_SLOTS_WIN               390 // MUS_ME_B_SMALL
#define MUS_TOO_BAD                 391 // MUS_ME_ZANNEN
#define MUS_ROULETTE                392 // MUS_BD_TIME
#define MUS_LINK_CONTEST_P1         393 // MUS_TEST1
#define MUS_LINK_CONTEST_P2         394 // MUS_TEST2
#define MUS_LINK_CONTEST_P3         395 // MUS_TEST3
#define MUS_LINK_CONTEST_P4         396 // MUS_TEST4
#define MUS_ENCOUNTER_RICH          397 // MUS_TEST
#define MUS_VERDANTURF              398 // MUS_GOMACHI0
#define MUS_RUSTBORO                399 // MUS_GOTOWN
#define MUS_POKE_CENTER             400 // MUS_POKECEN
#define MUS_ROUTE104                401 // MUS_NEXTROAD
#define MUS_ROUTE119                402 // MUS_GRANROAD
#define MUS_CYCLING                 403 // MUS_CYCLING
#define MUS_POKE_MART               404 // MUS_FRIENDLY
#define MUS_LITTLEROOT              405 // MUS_MISHIRO
#define MUS_MT_CHIMNEY              406 // MUS_TOZAN
#define MUS_ENCOUNTER_FEMALE        407 // MUS_GIRLEYE
#define MUS_LILYCOVE                408 // MUS_MINAMO
#define MUS_ROUTE111                409 // MUS_ASHROAD
#define MUS_HELP                    410 // MUS_EVENT0
#define MUS_UNDERWATER              411 // MUS_DEEPDEEP
#define MUS_VICTORY_TRAINER         412 // MUS_KACHI1
#define MUS_TITLE                   413 // MUS_TITLE3
#define MUS_INTRO                   414 // MUS_DEMO1
#define MUS_ENCOUNTER_MAY           415 // MUS_GIRL_SUP
#define MUS_ENCOUNTER_INTENSE       416 // MUS_HAGESHII
#define MUS_ENCOUNTER_COOL          417 // MUS_KAKKOII
#define MUS_ROUTE113                418 // MUS_KAZANBAI
#define MUS_ENCOUNTER_AQUA          419 // MUS_AQA_0
#define MUS_FOLLOW_ME               420 // MUS_TSURETEK
#define MUS_ENCOUNTER_BRENDAN       421 // MUS_BOY_SUP
#define MUS_EVER_GRANDE             422 // MUS_RAINBOW
#define MUS_ENCOUNTER_SUSPICIOUS    423 // MUS_AYASII
#define MUS_VICTORY_AQUA_MAGMA      424 // MUS_KACHI4
#define MUS_CABLE_CAR               425 // MUS_ROPEWAY
#define MUS_GAME_CORNER             426 // MUS_CASINO
#define MUS_DEWFORD                 427 // MUS_HIGHTOWN
#define MUS_SAFARI_ZONE             428 // MUS_SAFARI
#define MUS_VICTORY_ROAD            429 // MUS_C_ROAD
#define MUS_AQUA_MAGMA_HIDEOUT      430 // MUS_AJITO
#define MUS_SAILING                 431 // MUS_M_BOAT
#define MUS_MT_PYRE                 432 // MUS_M_DUNGON
#define MUS_SLATEPORT               433 // MUS_FINECITY
#define MUS_MT_PYRE_EXTERIOR        434 // MUS_MACHUPI
#define MUS_SCHOOL                  435 // MUS_P_SCHOOL
#define MUS_HALL_OF_FAME            436 // MUS_DENDOU
#define MUS_FALLARBOR               437 // MUS_TONEKUSA
#define MUS_SEALED_CHAMBER          438 // MUS_MABOROSI
#define MUS_CONTEST_WINNER          439 // MUS_CON_FAN
#define MUS_CONTEST                 440 // MUS_CONTEST0
#define MUS_ENCOUNTER_MAGMA         441 // MUS_MGM0
#define MUS_INTRO_BATTLE            442 // MUS_T_BATTLE
#define MUS_ABNORMAL_WEATHER        443 // MUS_OOAME (Replaces MUS_WEATHER_KYOGRE from R/S)
#define MUS_WEATHER_GROUDON         444 // MUS_HIDERI (Unused, from R/S)
#define MUS_SOOTOPOLIS              445 // MUS_RUNECITY
#define MUS_CONTEST_RESULTS         446 // MUS_CON_K
#define MUS_HALL_OF_FAME_ROOM       447 // MUS_EIKOU_R
#define MUS_TRICK_HOUSE             448 // MUS_KARAKURI
#define MUS_ENCOUNTER_TWINS         449 // MUS_HUTAGO
#define MUS_ENCOUNTER_ELITE_FOUR    450 // MUS_SITENNOU
#define MUS_ENCOUNTER_HIKER         451 // MUS_YAMA_EYE
#define MUS_CONTEST_LOBBY           452 // MUS_CONLOBBY
#define MUS_ENCOUNTER_INTERVIEWER   453 // MUS_INTER_V
#define MUS_ENCOUNTER_CHAMPION      454 // MUS_DAIGO
#define MUS_CREDITS                 455 // MUS_THANKFOR
#define MUS_END                     456 // MUS_END
#define MUS_B_FRONTIER              457 // MUS_B_FRONTIER
#define MUS_B_ARENA                 458 // MUS_B_ARENA
#define MUS_OBTAIN_B_POINTS         459 // MUS_ME_POINTGET
#define MUS_REGISTER_MATCH_CALL     460 // MUS_ME_TORE_EYE
#define MUS_B_PYRAMID               461 // MUS_PYRAMID
#define MUS_B_PYRAMID_TOP           462 // MUS_PYRAMID_TOP
#define MUS_B_PALACE                463 // MUS_B_PALACE
#define MUS_RAYQUAZA_APPEARS        464 // MUS_REKKUU_KOURIN
#define MUS_B_TOWER                 465 // MUS_SATTOWER
#define MUS_OBTAIN_SYMBOL           466 // MUS_ME_SYMBOLGET
#define MUS_B_DOME                  467 // MUS_B_DOME
#define MUS_B_PIKE                  468 // MUS_B_TUBE
#define MUS_B_FACTORY               469 // MUS_B_FACTORY
#define MUS_VS_RAYQUAZA             470 // MUS_VS_REKKU (Identical to MUS_VS_KYOGRE_GROUDON)
#define MUS_VS_FRONTIER_BRAIN       471 // MUS_VS_FRONT
#define MUS_VS_MEW                  472 // MUS_VS_MEW
#define MUS_B_DOME_LOBBY            473 // MUS_B_DOME1
#define MUS_VS_WILD                 474 // MUS_BATTLE27
#define MUS_VS_AQUA_MAGMA           475 // MUS_BATTLE31
#define MUS_VS_TRAINER              476 // MUS_BATTLE20
#define MUS_VS_GYM_LEADER           477 // MUS_BATTLE32
#define MUS_VS_CHAMPION             478 // MUS_BATTLE33
#define MUS_VS_REGI                 479 // MUS_BATTLE36
#define MUS_VS_KYOGRE_GROUDON       480 // MUS_BATTLE34
#define MUS_VS_RIVAL                481 // MUS_BATTLE35
#define MUS_VS_ELITE_FOUR           482 // MUS_BATTLE38
#define MUS_VS_AQUA_MAGMA_LEADER    483 // MUS_BATTLE30
// FRLG Music
#define MUS_RG_FOLLOW_ME            484 // MUS_RG_ANNAI
#define MUS_RG_GAME_CORNER          485 // MUS_RG_SLOT
#define MUS_RG_ROCKET_HIDEOUT       486 // MUS_RG_AJITO
#define MUS_RG_GYM                  487 // MUS_RG_GYM
#define MUS_RG_JIGGLYPUFF           488 // MUS_RG_PURIN
#define MUS_RG_INTRO_FIGHT          489 // MUS_RG_DEMO
#define MUS_RG_TITLE                490 // MUS_RG_TITLE
#define MUS_RG_CINNABAR             491 // MUS_RG_GUREN
#define MUS_RG_LAVENDER             492 // MUS_RG_SHION
#define MUS_RG_HEAL                 493 // MUS_RG_KAIHUKU
#define MUS_RG_CYCLING              494 // MUS_RG_CYCLING
#define MUS_RG_ENCOUNTER_ROCKET     495 // MUS_RG_ROCKET
#define MUS_RG_ENCOUNTER_GIRL       496 // MUS_RG_SHOUJO
#define MUS_RG_ENCOUNTER_BOY        497 // MUS_RG_SHOUNEN
#define MUS_RG_HALL_OF_FAME         498 // MUS_RG_DENDOU
#define MUS_RG_VIRIDIAN_FOREST      499 // MUS_RG_T_MORI
#define MUS_RG_MT_MOON              500 // MUS_RG_OTSUKIMI
#define MUS_RG_POKE_MANSION         501 // MUS_RG_POKEYASHI
#define MUS_RG_CREDITS              502 // MUS_RG_ENDING
#define MUS_RG_ROUTE1               503 // MUS_RG_LOAD01
#define MUS_RG_ROUTE24              504 // MUS_RG_OPENING
#define MUS_RG_ROUTE3               505 // MUS_RG_LOAD02
#define MUS_RG_ROUTE11              506 // MUS_RG_LOAD03
#define MUS_RG_VICTORY_ROAD         507 // MUS_RG_CHAMP_R
#define MUS_RG_VS_GYM_LEADER        508 // MUS_RG_VS_GYM
#define MUS_RG_VS_TRAINER           509 // MUS_RG_VS_TORE
#define MUS_RG_VS_WILD              510 // MUS_RG_VS_YASEI
#define MUS_RG_VS_CHAMPION          511 // MUS_RG_VS_LAST
#define MUS_RG_PALLET               512 // MUS_RG_MASARA
#define MUS_RG_OAK_LAB              513 // MUS_RG_KENKYU
#define MUS_RG_OAK                  514 // MUS_RG_OHKIDO
#define MUS_RG_POKE_CENTER          515 // MUS_RG_POKECEN
#define MUS_RG_SS_ANNE              516 // MUS_RG_SANTOAN
#define MUS_RG_SURF                 517 // MUS_RG_NAMINORI
#define MUS_RG_POKE_TOWER           518 // MUS_RG_P_TOWER
#define MUS_RG_SILPH                519 // MUS_RG_SHIRUHU
#define MUS_RG_FUCHSIA              520 // MUS_RG_HANADA
#define MUS_RG_CELADON              521 // MUS_RG_TAMAMUSI
#define MUS_RG_VICTORY_TRAINER      522 // MUS_RG_WIN_TRE (Identical to MUS_VICTORY_TRAINER)
#define MUS_RG_VICTORY_WILD         523 // MUS_RG_WIN_YASEI (Identical to MUS_VICTORY_WILD)
#define MUS_RG_VICTORY_GYM_LEADER   524 // MUS_RG_WIN_GYM (Identical to MUS_VICTORY_GYM_LEADER)
#define MUS_RG_VERMILLION           525 // MUS_RG_KUCHIBA
#define MUS_RG_PEWTER               526 // MUS_RG_NIBI
#define MUS_RG_ENCOUNTER_RIVAL      527 // MUS_RG_RIVAL1
#define MUS_RG_RIVAL_EXIT           528 // MUS_RG_RIVAL2
#define MUS_RG_DEX_RATING           529 // MUS_RG_FAN2
#define MUS_RG_OBTAIN_KEY_ITEM      530 // MUS_RG_FAN5
#define MUS_RG_CAUGHT_INTRO         531 // MUS_RG_FAN6
#define MUS_RG_PHOTO                532 // MUS_ME_RG_PHOTO
#define MUS_RG_GAME_FREAK           533 // MUS_RG_TITLEROG
#define MUS_RG_CAUGHT               534 // MUS_RG_GET_YASEI
#define MUS_RG_NEW_GAME_INSTRUCT    535 // MUS_RG_SOUSA
#define MUS_RG_NEW_GAME_INTRO       536 // MUS_RG_SEKAIKAN
#define MUS_RG_NEW_GAME_EXIT        537 // MUS_RG_SEIBETU
#define MUS_RG_POKE_JUMP            538 // MUS_RG_JUMP
#define MUS_RG_UNION_ROOM           539 // MUS_RG_UNION
#define MUS_RG_NET_CENTER           540 // MUS_RG_NETWORK
#define MUS_RG_MYSTERY_GIFT         541 // MUS_RG_OKURIMONO
#define MUS_RG_BERRY_PICK           542 // MUS_RG_KINOMIKUI
#define MUS_RG_SEVII_CAVE           543 // MUS_RG_NANADUNGEON (Identical to MUS_RG_MT_MOON)
#define MUS_RG_TEACHY_TV_SHOW       544 // MUS_RG_OSHIE_TV (Identical to MUS_RG_FOLLOW_ME)
#define MUS_RG_SEVII_ROUTE          545 // MUS_RG_NANASHIMA
#define MUS_RG_SEVII_DUNGEON        546 // MUS_RG_NANAISEKI (Identical to MUS_RG_VIRIDIAN_FOREST)
#define MUS_RG_SEVII_123            547 // MUS_RG_NANA123 (Identical to MUS_RG_PEWTER)
#define MUS_RG_SEVII_45             548 // MUS_RG_NANA45
#define MUS_RG_SEVII_67             549 // MUS_RG_NANA67
#define MUS_RG_POKE_FLUTE           550 // MUS_RG_POKEFUE
#define MUS_RG_VS_DEOXYS            551 // MUS_RG_VS_DEO
#define MUS_RG_VS_MEWTWO            552 // MUS_RG_VS_MYU2
#define MUS_RG_VS_LEGEND            553 // MUS_RG_VS_DEN
#define MUS_RG_ENCOUNTER_GYM_LEADER 554 // MUS_RG_EXEYE
#define MUS_RG_ENCOUNTER_DEOXYS     555 // MUS_RG_DEOEYE
#define MUS_RG_TRAINER_TOWER        556 // MUS_RG_T_TOWER
#define MUS_RG_SLOW_PALLET          557 // MUS_RG_SLOWMASARA
#define MUS_RG_TEACHY_TV_MENU       558 // MUS_RG_TVNOIZE

#define FIRST_SONG                  MUS_LITTLEROOT_TEST
#define SONG_COUNT                  MUS_RG_TEACHY_TV_MENU + 1 - FIRST_SONG

#define MUS_ROUTE118                0x7FFF  // Map is split into 2 music sections. controlled by GetCurrLocationDefaultMusic().

#define MUS_NONE                    0xFFFF

#endif  // GUARD_CONSTANTS_SONGS_H
