#ifndef GUARD_TRAINERS_H
#define GUARD_TRAINERS_H

#include "constants/opponents.h"
#include "constants/battle_frontier_trainers.h"

// Special Trainer Ids.
//      0-299 are frontier trainers
#define TRAINER_RECORD_MIXING_FRIEND        FRONTIER_TRAINERS_COUNT
#define TRAINER_RECORD_MIXING_APPRENTICE    400
#define TRAINER_EREADER                     500
#define TRAINER_FRONTIER_BRAIN              1022
#define TRAINER_PLAYER                      1023
#define TRAINER_LINK_OPPONENT               1024
#define TRAINER_UNION_ROOM                  2048
#define TRAINER_STEVEN_PARTNER              3072

// Trainer pics
#define TRAINER_PIC_HOENN_HIKER                 0
#define TRAINER_PIC_FIREBREATHER                1
#define TRAINER_PIC_HOENN_PKMN_BREEDER_F        2
#define TRAINER_PIC_HOENN_COOLTRAINER_M         3
#define TRAINER_PIC_HOENN_BIRD_KEEPER           4
#define TRAINER_PIC_HOENN_COLLECTOR             5
#define TRAINER_PIC_AQUA_GRUNT_F                6
#define TRAINER_PIC_HOENN_SWIMMER_M             7
#define TRAINER_PIC_MAGMA_GRUNT_M               8
#define TRAINER_PIC_HOENN_EXPERT_M              9
#define TRAINER_PIC_HOENN_BLACK_BELT            10
#define TRAINER_PIC_AQUA_LEADER                 11
#define TRAINER_PIC_HOENN_HEX_MANIAC            12
#define TRAINER_PIC_HOENN_AROMA_LADY            13
#define TRAINER_PIC_HOENN_RUIN_MANIAC           14
#define TRAINER_PIC_HOENN_INTERVIEWER           15
#define TRAINER_PIC_HOENN_TUBER_F               16
#define TRAINER_PIC_HOENN_TUBER_M               17
#define TRAINER_PIC_HOENN_COOLTRAINER_F         18
#define TRAINER_PIC_HOENN_LADY                  19
#define TRAINER_PIC_HOENN_BEAUTY                20
#define TRAINER_PIC_HOENN_RICH_BOY              21
#define TRAINER_PIC_HOENN_EXPERT_F              22
#define TRAINER_PIC_HOENN_POKEMANIAC            23
#define TRAINER_PIC_MAGMA_GRUNT_F               24
#define TRAINER_PIC_HOENN_GUITARIST             25
#define TRAINER_PIC_HOENN_KINDLER               26
#define TRAINER_PIC_HOENN_CAMPER                27
#define TRAINER_PIC_HOENN_PICNICKER             28
#define TRAINER_PIC_HOENN_BUG_MANIAC            29
#define TRAINER_PIC_HOENN_PSYCHIC_M             30
#define TRAINER_PIC_HOENN_PSYCHIC_F             31
#define TRAINER_PIC_HOENN_GENTLEMAN             32
#define TRAINER_PIC_ELITE_FOUR_SIDNEY           33
#define TRAINER_PIC_ELITE_FOUR_PHOEBE           34
#define TRAINER_PIC_LEADER_ROXANNE              35
#define TRAINER_PIC_LEADER_BRAWLY               36
#define TRAINER_PIC_LEADER_TATE_AND_LIZA        37
#define TRAINER_PIC_HOENN_SCHOOL_KID_M          38
#define TRAINER_PIC_HOENN_SCHOOL_KID_F          39
#define TRAINER_PIC_HOENN_SR_AND_JR             40
#define TRAINER_PIC_HOENN_POKEFAN_M             41
#define TRAINER_PIC_HOENN_POKEFAN_F             42
#define TRAINER_PIC_HOENN_YOUNGSTER             43
#define TRAINER_PIC_HOENN_CHAMPION              44
#define TRAINER_PIC_HOENN_FISHERMAN             45
#define TRAINER_PIC_HOENN_CYCLING_TRIATHLETE_M  46
#define TRAINER_PIC_HOENN_CYCLING_TRIATHLETE_F  47
#define TRAINER_PIC_HOENN_RUNNING_TRIATHLETE_M  48
#define TRAINER_PIC_HOENN_RUNNING_TRIATHLETE_F  49
#define TRAINER_PIC_HOENN_SWIMMING_TRIATHLETE_M 50
#define TRAINER_PIC_HOENN_SWIMMING_TRIATHLETE_F 51
#define TRAINER_PIC_HOENN_DRAGON_TAMER          52
#define TRAINER_PIC_HOENN_NINJA_BOY             53
#define TRAINER_PIC_HOENN_BATTLE_GIRL           54
#define TRAINER_PIC_HOENN_PARASOL_LADY          55
#define TRAINER_PIC_HOENN_SWIMMER_F             56
#define TRAINER_PIC_HOENN_TWINS                 57
#define TRAINER_PIC_HOENN_SAILOR                58
#define TRAINER_PIC_WALLY                       59
#define TRAINER_PIC_E_BRENDAN                   60
#define TRAINER_PIC_E_MAY                       61
#define TRAINER_PIC_HOENN_PKMN_BREEDER_M        62
#define TRAINER_PIC_HOENN_BUG_CATCHER           63
#define TRAINER_PIC_HOENN_PKMN_RANGER_M         64
#define TRAINER_PIC_HOENN_PKMN_RANGER_F         65
#define TRAINER_PIC_MAGMA_LEADER                66
#define TRAINER_PIC_HOENN_LASS                  67
#define TRAINER_PIC_HOENN_YOUNG_COUPLE          68
#define TRAINER_PIC_HOENN_OLD_COUPLE            69
#define TRAINER_PIC_HOENN_SIS_AND_BRO           70
#define TRAINER_PIC_STEVEN                      71
#define TRAINER_PIC_SALON_MAIDEN_ANABEL         72
#define TRAINER_PIC_DOME_ACE_TUCKER             73
#define TRAINER_PIC_GOLD                        74
#define TRAINER_PIC_KRIS                        75
#define TRAINER_PIC_H_BRENDAN                   76
#define TRAINER_PIC_H_MAY                       77
#define TRAINER_PIC_AQUA_ADMIN_M                78
#define TRAINER_PIC_AQUA_ADMIN_F                79
#define TRAINER_PIC_MAGMA_ADMIN                 80
#define TRAINER_PIC_LEADER_WATTSON              81
#define TRAINER_PIC_LEADER_FLANNERY             82
#define TRAINER_PIC_LEADER_NORMAN               83
#define TRAINER_PIC_LEADER_WINONA               84
#define TRAINER_PIC_LEADER_JUAN                 85
#define TRAINER_PIC_ELITE_FOUR_GLACIA           86
#define TRAINER_PIC_ELITE_FOUR_DRAKE            87
#define TRAINER_PIC_PALACE_MAVEN_SPENSER        88
#define TRAINER_PIC_ARENA_TYCOON_GRETA          89
#define TRAINER_PIC_FACTORY_HEAD_NOLAND         90
#define TRAINER_PIC_PIKE_QUEEN_LUCY             91
#define TRAINER_PIC_PYRAMID_KING_BRANDON        92

// FRLG trainer pics
#define TRAINER_PIC_YOUNGSTER                   93
#define TRAINER_PIC_BUG_CATCHER                 94
#define TRAINER_PIC_LASS                        95
#define TRAINER_PIC_SAILOR                      96
#define TRAINER_PIC_CAMPER                      97
#define TRAINER_PIC_PICNICKER                   98
#define TRAINER_PIC_POKEMANIAC                  99
#define TRAINER_PIC_SUPER_NERD                  100
#define TRAINER_PIC_HIKER                       101
#define TRAINER_PIC_BIKER                       102
#define TRAINER_PIC_BURGLAR                     103
#define TRAINER_PIC_ENGINEER                    104
#define TRAINER_PIC_FISHERMAN                   105
#define TRAINER_PIC_SWIMMER_M                   106
#define TRAINER_PIC_CUE_BALL                    107
#define TRAINER_PIC_GAMER                       108
#define TRAINER_PIC_BEAUTY                      109
#define TRAINER_PIC_SWIMMER_F                   110
#define TRAINER_PIC_PSYCHIC_M                   111
#define TRAINER_PIC_ROCKER                      112
#define TRAINER_PIC_JUGGLER                     113
#define TRAINER_PIC_TAMER                       114
#define TRAINER_PIC_BIRD_KEEPER                 115
#define TRAINER_PIC_BLACK_BELT                  116
#define TRAINER_PIC_RIVAL_1                     117
#define TRAINER_PIC_SCIENTIST                   118
#define TRAINER_PIC_LEADER_GIOVANNI             119
#define TRAINER_PIC_ROCKET_GRUNT_M              120
#define TRAINER_PIC_COOLTRAINER_M               121
#define TRAINER_PIC_COOLTRAINER_F               122
#define TRAINER_PIC_ELITE_FOUR_LORELEI          123
#define TRAINER_PIC_ELITE_FOUR_BRUNO            124
#define TRAINER_PIC_ELITE_FOUR_AGATHA           125
#define TRAINER_PIC_ELITE_FOUR_LANCE            126
#define TRAINER_PIC_LEADER_BROCK                127
#define TRAINER_PIC_LEADER_MISTY                128
#define TRAINER_PIC_LEADER_LT_SURGE             129
#define TRAINER_PIC_LEADER_ERIKA                130
#define TRAINER_PIC_LEADER_KOGA                 131
#define TRAINER_PIC_LEADER_BLAINE               132
#define TRAINER_PIC_LEADER_SABRINA              133
#define TRAINER_PIC_GENTLEMAN                   134
#define TRAINER_PIC_RIVAL_2                     135
#define TRAINER_PIC_CHAMPION_RIVAL              136
#define TRAINER_PIC_CHANNELER                   137
#define TRAINER_PIC_TWINS                       138
#define TRAINER_PIC_COOL_COUPLE                 139
#define TRAINER_PIC_YOUNG_COUPLE                140
#define TRAINER_PIC_CRUSH_KIN                   141
#define TRAINER_PIC_SIS_AND_BRO                 142
#define TRAINER_PIC_PROFESSOR_OAK               143
#define TRAINER_PIC_RS_BRENDAN                  144
#define TRAINER_PIC_RS_MAY                      145
#define TRAINER_PIC_RED_ORIGINAL                146
#define TRAINER_PIC_LEAF_ORIGINAL               147
#define TRAINER_PIC_ROCKET_GRUNT_F              148
#define TRAINER_PIC_PSYCHIC_F                   149
#define TRAINER_PIC_CRUSH_GIRL                  150
#define TRAINER_PIC_TUBER_F                     151
#define TRAINER_PIC_PKMN_BREEDER_F              152
#define TRAINER_PIC_PKMN_RANGER_M               153
#define TRAINER_PIC_PKMN_RANGER_F               154
#define TRAINER_PIC_AROMA_LADY                  155
#define TRAINER_PIC_RUIN_MANIAC                 156
#define TRAINER_PIC_LADY                        157
#define TRAINER_PIC_PAINTER                     158
#define TRAINER_PIC_RED                         159
#define TRAINER_PIC_LEAF                        160
#define TRAINER_PIC_RED_DX                      161
#define TRAINER_PIC_LEAF_DX                     162
#define TRAINER_PIC_RED_CLASSIC                 163
#define TRAINER_PIC_LEAF_CLASSIC                164
#define TRAINER_PIC_RED_ALOLA                   165
#define TRAINER_PIC_LEAF_ALOLA                  166
#define TRAINER_PIC_RED_SYGNA_SUIT              167
#define TRAINER_PIC_LEAF_SYGNA_SUIT             168
#define TRAINER_PIC_RED_TEAM_ROCKET             169
#define TRAINER_PIC_LEAF_TEAM_ROCKET            170
#define TRAINER_PIC_RED_TEAM_AQUA               171
#define TRAINER_PIC_LEAF_TEAM_AQUA              172
#define TRAINER_PIC_RED_TEAM_MAGMA              173
#define TRAINER_PIC_LEAF_TEAM_MAGMA             174
#define TRAINER_PIC_PKMN_FAN_CLUB_PRESIDENT     175
#define TRAINER_PIC_TUBER_M                     176
#define TRAINER_PIC_ROCKET_ADMIN_PROTON         177
#define TRAINER_PIC_ROCKET_ADMIN_PETREL         178
#define TRAINER_PIC_ROCKET_ADMIN_ARCHER         179
#define TRAINER_PIC_ROCKET_ADMIN_ARIANA         180
#define TRAINER_PIC_DAISY                       181
#define TRAINER_PIC_BILL                        182
#define TRAINER_PIC_MR_FUJI                     183
#define TRAINER_PIC_SCOTT                       184

#define TRAINER_PIC_COUNT                       (TRAINER_PIC_SCOTT + 1)

// The player back pics are assumed to alternate according to the gender values (MALE/FEMALE)
#define TRAINER_BACK_PIC_RED_ORIGINAL            0
#define TRAINER_BACK_PIC_LEAF_ORIGINAL           1
#define TRAINER_BACK_PIC_POKE_DUDE               2
#define TRAINER_BACK_PIC_OLD_MAN                 3
#define TRAINER_BACK_PIC_E_BRENDAN               4
#define TRAINER_BACK_PIC_E_MAY                   5
#define TRAINER_BACK_PIC_RS_BRENDAN              6
#define TRAINER_BACK_PIC_RS_MAY                  7
#define TRAINER_BACK_PIC_WALLY                   8
#define TRAINER_BACK_PIC_STEVEN                  9

#define TRAINER_BACK_PIC_H_BRENDAN               10
#define TRAINER_BACK_PIC_H_MAY                   11
#define TRAINER_BACK_PIC_GOLD                    12
#define TRAINER_BACK_PIC_KRIS                    13
#define TRAINER_BACK_PIC_LANCE                   14

#define TRAINER_BACK_PIC_RED                     15
#define TRAINER_BACK_PIC_LEAF                    16
#define TRAINER_BACK_PIC_RED_DX                  17
#define TRAINER_BACK_PIC_LEAF_DX                 18
#define TRAINER_BACK_PIC_RED_CLASSIC             19
#define TRAINER_BACK_PIC_LEAF_CLASSIC            20
#define TRAINER_BACK_PIC_RED_ALOLA               21
#define TRAINER_BACK_PIC_LEAF_ALOLA              22
#define TRAINER_BACK_PIC_RED_SYGNA_SUIT          23
#define TRAINER_BACK_PIC_LEAF_SYGNA_SUIT         24
#define TRAINER_BACK_PIC_RED_TEAM_ROCKET         25
#define TRAINER_BACK_PIC_LEAF_TEAM_ROCKET        26
#define TRAINER_BACK_PIC_RED_TEAM_AQUA           27
#define TRAINER_BACK_PIC_LEAF_TEAM_AQUA          28
#define TRAINER_BACK_PIC_RED_TEAM_MAGMA          29
#define TRAINER_BACK_PIC_LEAF_TEAM_MAGMA         30

// Facility classes
#define FACILITY_CLASS_HOENN_HIKER                 0
#define FACILITY_CLASS_FIREBREATHER                1
#define FACILITY_CLASS_HOENN_PKMN_BREEDER_F        2
#define FACILITY_CLASS_HOENN_COOLTRAINER_M         3
#define FACILITY_CLASS_HOENN_BIRD_KEEPER           4
#define FACILITY_CLASS_HOENN_COLLECTOR             5
#define FACILITY_CLASS_AQUA_GRUNT_F                6
#define FACILITY_CLASS_HOENN_SWIMMER_M             7
#define FACILITY_CLASS_MAGMA_GRUNT_M               8
#define FACILITY_CLASS_HOENN_EXPERT_M              9
#define FACILITY_CLASS_HOENN_BLACK_BELT            10
#define FACILITY_CLASS_AQUA_LEADER                 11
#define FACILITY_CLASS_HOENN_HEX_MANIAC            12
#define FACILITY_CLASS_HOENN_AROMA_LADY            13
#define FACILITY_CLASS_HOENN_RUIN_MANIAC           14
#define FACILITY_CLASS_HOENN_INTERVIEWER           15
#define FACILITY_CLASS_HOENN_TUBER_F               16
#define FACILITY_CLASS_HOENN_TUBER_M               17
#define FACILITY_CLASS_HOENN_COOLTRAINER_F         18
#define FACILITY_CLASS_HOENN_LADY                  19
#define FACILITY_CLASS_HOENN_BEAUTY                20
#define FACILITY_CLASS_HOENN_RICH_BOY              21
#define FACILITY_CLASS_HOENN_EXPERT_F              22
#define FACILITY_CLASS_HOENN_POKEMANIAC            23
#define FACILITY_CLASS_MAGMA_GRUNT_F               24
#define FACILITY_CLASS_HOENN_GUITARIST             25
#define FACILITY_CLASS_HOENN_KINDLER               26
#define FACILITY_CLASS_HOENN_CAMPER                27
#define FACILITY_CLASS_HOENN_PICNICKER             28
#define FACILITY_CLASS_HOENN_BUG_MANIAC            29
#define FACILITY_CLASS_HOENN_PSYCHIC_M             30
#define FACILITY_CLASS_HOENN_PSYCHIC_F             31
#define FACILITY_CLASS_HOENN_GENTLEMAN             32
#define FACILITY_CLASS_ELITE_FOUR_SIDNEY           33
#define FACILITY_CLASS_ELITE_FOUR_PHOEBE           34
#define FACILITY_CLASS_LEADER_ROXANNE              35
#define FACILITY_CLASS_LEADER_BRAWLY               36
#define FACILITY_CLASS_LEADER_TATE_AND_LIZA        37
#define FACILITY_CLASS_HOENN_SCHOOL_KID_M          38
#define FACILITY_CLASS_HOENN_SCHOOL_KID_F          39
#define FACILITY_CLASS_HOENN_SR_AND_JR             40
#define FACILITY_CLASS_HOENN_POKEFAN_M             41
#define FACILITY_CLASS_HOENN_POKEFAN_F             42
#define FACILITY_CLASS_HOENN_YOUNGSTER             43
#define FACILITY_CLASS_HOENN_CHAMPION              44
#define FACILITY_CLASS_HOENN_FISHERMAN             45
#define FACILITY_CLASS_HOENN_CYCLING_TRIATHLETE_M  46
#define FACILITY_CLASS_HOENN_CYCLING_TRIATHLETE_F  47
#define FACILITY_CLASS_HOENN_RUNNING_TRIATHLETE_M  48
#define FACILITY_CLASS_HOENN_RUNNING_TRIATHLETE_F  49
#define FACILITY_CLASS_HOENN_SWIMMING_TRIATHLETE_M 50
#define FACILITY_CLASS_HOENN_SWIMMING_TRIATHLETE_F 51
#define FACILITY_CLASS_HOENN_DRAGON_TAMER          52
#define FACILITY_CLASS_HOENN_NINJA_BOY             53
#define FACILITY_CLASS_HOENN_BATTLE_GIRL           54
#define FACILITY_CLASS_HOENN_PARASOL_LADY          55
#define FACILITY_CLASS_HOENN_SWIMMER_F             56
#define FACILITY_CLASS_HOENN_TWINS                 57
#define FACILITY_CLASS_HOENN_SAILOR                58
#define FACILITY_CLASS_WALLY                       59
#define FACILITY_CLASS_E_BRENDAN                   60
#define FACILITY_CLASS_BRENDAN_2                   61
#define FACILITY_CLASS_BRENDAN_3                   62
#define FACILITY_CLASS_E_MAY                       63
#define FACILITY_CLASS_MAY_2                       64
#define FACILITY_CLASS_MAY_3                       65
#define FACILITY_CLASS_HOENN_PKMN_BREEDER_M        66
#define FACILITY_CLASS_HOENN_BUG_CATCHER           67
#define FACILITY_CLASS_HOENN_PKMN_RANGER_M         68
#define FACILITY_CLASS_HOENN_PKMN_RANGER_F         69
#define FACILITY_CLASS_MAGMA_LEADER                70
#define FACILITY_CLASS_HOENN_LASS                  71
#define FACILITY_CLASS_HOENN_YOUNG_COUPLE          72
#define FACILITY_CLASS_HOENN_OLD_COUPLE            73
#define FACILITY_CLASS_HOENN_SIS_AND_BRO           74
#define FACILITY_CLASS_STEVEN                      75
#define FACILITY_CLASS_SALON_MAIDEN_ANABEL         76
#define FACILITY_CLASS_DOME_ACE_TUCKER             77
#define FACILITY_CLASS_GOLD                        78
#define FACILITY_CLASS_KRIS                        79
#define FACILITY_CLASS_H_BRENDAN                   80
#define FACILITY_CLASS_H_MAY                       81

#define FACILITY_CLASSES_HOENN_COUNT               (FACILITY_CLASS_H_MAY + 1)

#define FACILITY_CLASS_AQUA_ADMIN_M                82
#define FACILITY_CLASS_AQUA_ADMIN_F                83
#define FACILITY_CLASS_MAGMA_ADMIN                 84
#define FACILITY_CLASS_LEADER_WATTSON              85
#define FACILITY_CLASS_LEADER_FLANNERY             86
#define FACILITY_CLASS_LEADER_NORMAN               87
#define FACILITY_CLASS_LEADER_WINONA               88
#define FACILITY_CLASS_LEADER_JUAN                 89
#define FACILITY_CLASS_ELITE_FOUR_GLACIA           90
#define FACILITY_CLASS_ELITE_FOUR_DRAKE            91
#define FACILITY_CLASS_PALACE_MAVEN_SPENSER        92
#define FACILITY_CLASS_ARENA_TYCOON_GRETA          93
#define FACILITY_CLASS_FACTORY_HEAD_NOLAND         94
#define FACILITY_CLASS_PIKE_QUEEN_LUCY             95
#define FACILITY_CLASS_PYRAMID_KING_BRANDON        96

// FRLG facility classes
#define FACILITY_CLASS_YOUNGSTER                   97
#define FACILITY_CLASS_BUG_CATCHER                 98
#define FACILITY_CLASS_LASS                        99
#define FACILITY_CLASS_SAILOR                      100
#define FACILITY_CLASS_CAMPER                      101
#define FACILITY_CLASS_PICNICKER                   102
#define FACILITY_CLASS_POKEMANIAC                  103
#define FACILITY_CLASS_SUPER_NERD                  104
#define FACILITY_CLASS_HIKER                       105
#define FACILITY_CLASS_BIKER                       106
#define FACILITY_CLASS_BURGLAR                     107
#define FACILITY_CLASS_ENGINEER                    108
#define FACILITY_CLASS_FISHERMAN                   109
#define FACILITY_CLASS_SWIMMER_M                   110
#define FACILITY_CLASS_CUE_BALL                    111
#define FACILITY_CLASS_GAMER                       112
#define FACILITY_CLASS_BEAUTY                      113
#define FACILITY_CLASS_SWIMMER_F                   114
#define FACILITY_CLASS_PSYCHIC_M                   115
#define FACILITY_CLASS_ROCKER                      116
#define FACILITY_CLASS_JUGGLER                     117
#define FACILITY_CLASS_TAMER                       118
#define FACILITY_CLASS_BIRD_KEEPER                 119
#define FACILITY_CLASS_BLACK_BELT                  120
#define FACILITY_CLASS_SCIENTIST                   121
#define FACILITY_CLASS_COOLTRAINER_M               122
#define FACILITY_CLASS_COOLTRAINER_F               123
#define FACILITY_CLASS_GENTLEMAN                   124
#define FACILITY_CLASS_CHANNELER                   125
#define FACILITY_CLASS_TWINS                       126
#define FACILITY_CLASS_COOL_COUPLE                 127
#define FACILITY_CLASS_YOUNG_COUPLE                128
#define FACILITY_CLASS_CRUSH_KIN                   129
#define FACILITY_CLASS_RS_BRENDAN                  130
#define FACILITY_CLASS_RS_MAY                      131
#define FACILITY_CLASS_RED_ORIGINAL                132
#define FACILITY_CLASS_LEAF_ORIGINAL               133
#define FACILITY_CLASS_PSYCHIC_F                   134
#define FACILITY_CLASS_CRUSH_GIRL                  135
#define FACILITY_CLASS_TUBER_F                     136
#define FACILITY_CLASS_PKMN_BREEDER_F              137
#define FACILITY_CLASS_PKMN_RANGER_M               138
#define FACILITY_CLASS_PKMN_RANGER_F               139
#define FACILITY_CLASS_AROMA_LADY                  140
#define FACILITY_CLASS_RUIN_MANIAC                 141
#define FACILITY_CLASS_LADY                        142
#define FACILITY_CLASS_PAINTER                     143

#define FACILITY_CLASS_RED                         144
#define FACILITY_CLASS_LEAF                        145
#define FACILITY_CLASS_RED_DX                      146
#define FACILITY_CLASS_LEAF_DX                     147
#define FACILITY_CLASS_RED_CLASSIC                 148
#define FACILITY_CLASS_LEAF_CLASSIC                149
#define FACILITY_CLASS_RED_ALOLA                   150
#define FACILITY_CLASS_LEAF_ALOLA                  151
#define FACILITY_CLASS_RED_SYGNA_SUIT              152
#define FACILITY_CLASS_LEAF_SYGNA_SUIT             153
#define FACILITY_CLASS_RED_TEAM_ROCKET             154
#define FACILITY_CLASS_LEAF_TEAM_ROCKET            155
#define FACILITY_CLASS_RED_TEAM_AQUA               156
#define FACILITY_CLASS_LEAF_TEAM_AQUA              157
#define FACILITY_CLASS_RED_TEAM_MAGMA              158
#define FACILITY_CLASS_LEAF_TEAM_MAGMA             159

#define FACILITY_CLASSES_COUNT                     (FACILITY_CLASS_LEAF_TEAM_MAGMA + 1)

#define RS_FACILITY_CLASS_AQUA_LEADER_ARCHIE    0
#define RS_FACILITY_CLASS_AQUA_GRUNT_M          1
#define RS_FACILITY_CLASS_AQUA_GRUNT_F          2
#define RS_FACILITY_CLASS_AROMA_LADY            3
#define RS_FACILITY_CLASS_RUIN_MANIAC           4
#define RS_FACILITY_CLASS_INTERVIEWER           5
#define RS_FACILITY_CLASS_TUBER_F               6
#define RS_FACILITY_CLASS_TUBER_M               7
#define RS_FACILITY_CLASS_COOLTRAINER_M         8
#define RS_FACILITY_CLASS_COOLTRAINER_F         9
#define RS_FACILITY_CLASS_HEX_MANIAC            10
#define RS_FACILITY_CLASS_LADY                  11
#define RS_FACILITY_CLASS_BEAUTY                12
#define RS_FACILITY_CLASS_RICH_BOY              13
#define RS_FACILITY_CLASS_POKEMANIAC            14
#define RS_FACILITY_CLASS_SWIMMER_M             15
#define RS_FACILITY_CLASS_BLACK_BELT            16
#define RS_FACILITY_CLASS_GUITARIST             17
#define RS_FACILITY_CLASS_KINDLER               18
#define RS_FACILITY_CLASS_CAMPER                19
#define RS_FACILITY_CLASS_BUG_MANIAC            20
#define RS_FACILITY_CLASS_PSYCHIC_M             21
#define RS_FACILITY_CLASS_PSYCHIC_F             22
#define RS_FACILITY_CLASS_GENTLEMAN             23
#define RS_FACILITY_CLASS_ELITE_FOUR_M          24
#define RS_FACILITY_CLASS_ELITE_FOUR_F          25
#define RS_FACILITY_CLASS_LEADER_F              26
#define RS_FACILITY_CLASS_LEADER_M              27
#define RS_FACILITY_CLASS_LEADER_MF             28
#define RS_FACILITY_CLASS_SCHOOL_KID_M          29
#define RS_FACILITY_CLASS_SCHOOL_KID_F          30
#define RS_FACILITY_CLASS_SR_AND_JR             31
#define RS_FACILITY_CLASS_POKEFAN_M             32
#define RS_FACILITY_CLASS_POKEFAN_F             33
#define RS_FACILITY_CLASS_EXPERT_M              34
#define RS_FACILITY_CLASS_EXPERT_F              35
#define RS_FACILITY_CLASS_YOUNGSTER             36
#define RS_FACILITY_CLASS_CHAMPION              37
#define RS_FACILITY_CLASS_FISHERMAN             38
#define RS_FACILITY_CLASS_CYCLING_TRIATHLETE_M  39
#define RS_FACILITY_CLASS_CYCLING_TRIATHLETE_F  40
#define RS_FACILITY_CLASS_RUNNING_TRIATHLETE_M  41
#define RS_FACILITY_CLASS_RUNNING_TRIATHLETE_F  42
#define RS_FACILITY_CLASS_SWIMMING_TRIATHLETE_M 43
#define RS_FACILITY_CLASS_SWIMMING_TRIATHLETE_F 44
#define RS_FACILITY_CLASS_DRAGON_TAMER          45
#define RS_FACILITY_CLASS_BIRD_KEEPER           46
#define RS_FACILITY_CLASS_NINJA_BOY             47
#define RS_FACILITY_CLASS_BATTLE_GIRL           48
#define RS_FACILITY_CLASS_PARASOL_LADY          49
#define RS_FACILITY_CLASS_SWIMMER_F             50
#define RS_FACILITY_CLASS_PICNICKER             51
#define RS_FACILITY_CLASS_TWINS                 52
#define RS_FACILITY_CLASS_SAILOR                53
#define RS_FACILITY_CLASS_BOARDER_1             54
#define RS_FACILITY_CLASS_BOARDER_2             55
#define RS_FACILITY_CLASS_COLLECTOR             56
#define RS_FACILITY_CLASS_WALLY                 57
#define RS_FACILITY_CLASS_BRENDAN_1             58
#define RS_FACILITY_CLASS_BRENDAN_2             59
#define RS_FACILITY_CLASS_BRENDAN_3             60
#define RS_FACILITY_CLASS_MAY_1                 61
#define RS_FACILITY_CLASS_MAY_2                 62
#define RS_FACILITY_CLASS_MAY_3                 63
#define RS_FACILITY_CLASS_PKMN_BREEDER_M        64
#define RS_FACILITY_CLASS_PKMN_BREEDER_F        65
#define RS_FACILITY_CLASS_PKMN_RANGER_M         66
#define RS_FACILITY_CLASS_PKMN_RANGER_F         67
#define RS_FACILITY_CLASS_MAGMA_LEADER          68
#define RS_FACILITY_CLASS_MAGMA_GRUNT_M         69
#define RS_FACILITY_CLASS_MAGMA_GRUNT_F         70
#define RS_FACILITY_CLASS_LASS                  71
#define RS_FACILITY_CLASS_BUG_CATCHER           72
#define RS_FACILITY_CLASS_HIKER                 73
#define RS_FACILITY_CLASS_YOUNG_COUPLE          74
#define RS_FACILITY_CLASS_OLD_COUPLE            75
#define RS_FACILITY_CLASS_SIS_AND_BRO           76

#define RS_FACILITY_CLASSES_COUNT               (RS_FACILITY_CLASS_SIS_AND_BRO + 1)

#define TRAINER_CLASS_HIKER                  0
#define TRAINER_CLASS_FIREBREATHER           1
#define TRAINER_CLASS_PKMN_BREEDER           2
#define TRAINER_CLASS_COOLTRAINER            3
#define TRAINER_CLASS_BIRD_KEEPER            4
#define TRAINER_CLASS_HOENN_COLLECTOR        5
#define TRAINER_CLASS_SWIMMER_M              6
#define TRAINER_CLASS_TEAM_MAGMA             7
#define TRAINER_CLASS_HOENN_EXPERT           8
#define TRAINER_CLASS_BLACK_BELT             9
#define TRAINER_CLASS_AQUA_LEADER           10
#define TRAINER_CLASS_HOENN_HEX_MANIAC      11
#define TRAINER_CLASS_AROMA_LADY            12
#define TRAINER_CLASS_RUIN_MANIAC           13
#define TRAINER_CLASS_HOENN_INTERVIEWER     14
#define TRAINER_CLASS_TUBER                 15
#define TRAINER_CLASS_LADY                  16
#define TRAINER_CLASS_BEAUTY                17
#define TRAINER_CLASS_HOENN_RICH_BOY        18
#define TRAINER_CLASS_POKEMANIAC            19
#define TRAINER_CLASS_HOENN_GUITARIST       20
#define TRAINER_CLASS_HOENN_KINDLER         21
#define TRAINER_CLASS_CAMPER                22
#define TRAINER_CLASS_PICNICKER             23
#define TRAINER_CLASS_HOENN_BUG_MANIAC      24
#define TRAINER_CLASS_PSYCHIC               25
#define TRAINER_CLASS_GENTLEMAN             26
#define TRAINER_CLASS_ELITE_FOUR            27
#define TRAINER_CLASS_LEADER                28
#define TRAINER_CLASS_HOENN_SCHOOL_KID      29
#define TRAINER_CLASS_HOENN_SR_AND_JR       30
#define TRAINER_CLASS_HOENN_POKEFAN         31
#define TRAINER_CLASS_YOUNGSTER             32
#define TRAINER_CLASS_CHAMPION              33
#define TRAINER_CLASS_FISHERMAN             34
#define TRAINER_CLASS_HOENN_TRIATHLETE      35
#define TRAINER_CLASS_HOENN_DRAGON_TAMER    36
#define TRAINER_CLASS_HOENN_NINJA_BOY       37
#define TRAINER_CLASS_HOENN_BATTLE_GIRL     38
#define TRAINER_CLASS_HOENN_PARASOL_LADY    39
#define TRAINER_CLASS_SWIMMER_F             40
#define TRAINER_CLASS_TWINS                 41
#define TRAINER_CLASS_SAILOR                42
#define TRAINER_CLASS_PKMN_TRAINER          43
#define TRAINER_CLASS_BUG_CATCHER           44
#define TRAINER_CLASS_PKMN_RANGER           45
#define TRAINER_CLASS_MAGMA_LEADER          46
#define TRAINER_CLASS_LASS                  47
#define TRAINER_CLASS_YOUNG_COUPLE          48
#define TRAINER_CLASS_HOENN_OLD_COUPLE      49
#define TRAINER_CLASS_SIS_AND_BRO           50
#define TRAINER_CLASS_SALON_MAIDEN          51
#define TRAINER_CLASS_DOME_ACE              52
#define TRAINER_CLASS_AQUA_ADMIN            53
#define TRAINER_CLASS_MAGMA_ADMIN           54
#define TRAINER_CLASS_PALACE_MAVEN          55
#define TRAINER_CLASS_ARENA_TYCOON          56
#define TRAINER_CLASS_FACTORY_HEAD          57
#define TRAINER_CLASS_PIKE_QUEEN            58
#define TRAINER_CLASS_PYRAMID_KING          59
#define TRAINER_CLASS_SUPER_NERD            60
#define TRAINER_CLASS_BIKER                 61
#define TRAINER_CLASS_BURGLAR               62
#define TRAINER_CLASS_ENGINEER              63
#define TRAINER_CLASS_CUE_BALL              64
#define TRAINER_CLASS_GAMER                 65
#define TRAINER_CLASS_ROCKER                66
#define TRAINER_CLASS_JUGGLER               67
#define TRAINER_CLASS_TAMER                 68
#define TRAINER_CLASS_RIVAL_1               69
#define TRAINER_CLASS_SCIENTIST             70
#define TRAINER_CLASS_BOSS                  71
#define TRAINER_CLASS_TEAM_ROCKET           72
#define TRAINER_CLASS_RIVAL_2               73
#define TRAINER_CLASS_CHANNELER             74
#define TRAINER_CLASS_COOL_COUPLE           75
#define TRAINER_CLASS_CRUSH_KIN             76
#define TRAINER_CLASS_PKMN_PROF             77
#define TRAINER_CLASS_CRUSH_GIRL            78
#define TRAINER_CLASS_PAINTER               79
#define TRAINER_CLASS_PKMN_FAN_CLUB         80
#define TRAINER_CLASS_ROCKET_ADMIN          81

#define TRAINER_ENCOUNTER_MUSIC_MALE         0 // standard male encounter music
#define TRAINER_ENCOUNTER_MUSIC_FEMALE       1 // standard female encounter music
#define TRAINER_ENCOUNTER_MUSIC_GIRL         2 // used for male Tubers and Young Couples too
#define TRAINER_ENCOUNTER_MUSIC_SUSPICIOUS   3
#define TRAINER_ENCOUNTER_MUSIC_INTENSE      4
#define TRAINER_ENCOUNTER_MUSIC_COOL         5
#define TRAINER_ENCOUNTER_MUSIC_AQUA         6
#define TRAINER_ENCOUNTER_MUSIC_MAGMA        7
#define TRAINER_ENCOUNTER_MUSIC_SWIMMER      8
#define TRAINER_ENCOUNTER_MUSIC_TWINS        9 // used for other trainer classes too
#define TRAINER_ENCOUNTER_MUSIC_ELITE_FOUR  10
#define TRAINER_ENCOUNTER_MUSIC_HIKER       11 // used for other trainer classes too
#define TRAINER_ENCOUNTER_MUSIC_INTERVIEWER 12
#define TRAINER_ENCOUNTER_MUSIC_RICH        13 // Rich Boys and Gentlemen

#define F_TRAINER_FEMALE (1 << 7)

// All trainer parties specify the IV, level, and species for each Pokémon in the
// party. Some trainer parties also specify held items and custom moves for each
// Pokémon.
#define F_TRAINER_PARTY_CUSTOM_MOVESET (1 << 0)
#define F_TRAINER_PARTY_HELD_ITEM      (1 << 1)

#endif  // GUARD_TRAINERS_H
