Underwater_SealedChamber_Braille_GoUpHere: @ 82A6B15
	.braille "GO UP HERE.$"

SealedChamber_OuterRoom_Braille_ABC: @ 82A6B27
	.braille "ABC$"

SealedChamber_OuterRoom_Braille_GHI: @ 82A6B31
	.braille "GHI$"

SealedChamber_OuterRoom_Braille_MNO: @ 82A6B3B
	.braille "MNO$"

SealedChamber_OuterRoom_Braille_TUV: @ 82A6B45
	.braille "TUV$"

SealedChamber_OuterRoom_Braille_DEF: @ 82A6B4F
	.braille "DEF$"

SealedChamber_OuterRoom_Braille_JKL: @ 82A6B59
	.braille "JKL$"

SealedChamber_OuterRoom_Braille_PQRS: @ 82A6B63
	.braille "PQRS$"

SealedChamber_OuterRoom_Braille_Period: @ 82A6B6E
	.braille ".$"

SealedChamber_OuterRoom_Braille_WXYZ: @ 82A6B76
	.braille "WXYZ$"

SealedChamber_OuterRoom_Braille_Comma: @ 82A6B81
	.braille ",$"

SealedChamber_OuterRoom_Braille_DigHere: @ 82A6B89
	.braille "DIG HERE.$"

SealedChamber_InnerRoom_Braille_FirstWailordLastRelicanth: @ 82A6B99
	.braille "FIRST COMES\n"
	.braille "WAILORD.\n"
	.braille "LAST COMES\n"
	.braille "RELICANTH.$"

SealedChamber_InnerRoom_Braille_InThisCaveWeHaveLived: @ 82A6BCA
	.braille "IN THIS\n"
	.braille "CAVE WE\n"
	.braille "HAVE\n"
	.braille "LIVED.$"

SealedChamber_InnerRoom_Braille_WeOweAllToThePokemon: @ 82A6BEC
	.braille "WE OWE ALL\n"
	.braille "TO THE\n"
	.braille "POKEMON.$"

SealedChamber_InnerRoom_Braille_ButWeSealedThePokemonAway: @ 82A6C0D
	.braille "BUT, WE\n"
	.braille "SEALED THE\n"
	.braille "POKEMON\n"
	.braille "AWAY.$"

SealedChamber_InnerRoom_Braille_WeFearedIt: @ 82A6C34
	.braille "WE FEARED IT.$"

SealedChamber_InnerRoom_Braille_ThoseWithCourageHope: @ 82A6C48
	.braille "THOSE WITH\n"
	.braille "COURAGE,\n"
	.braille "THOSE WITH\n"
	.braille "HOPE.$"

SealedChamber_InnerRoom_Braille_OpenDoorEternalPokemonWaits: @ 82A6C73
	.braille "OPEN A DOOR.\n"
	.braille "AN ETERNAL\n"
	.braille "POKEMON\n"
	.braille "WAITS.$"

DesertRuins_Braille_UseRockSmash: @ 82A6CA0
	.braille "LEFT, LEFT,\n"
	.braille "DOWN, DOWN.\n"
	.braille "THEN, USE\n"
	.braille "ROCK SMASH.$"

IslandCave_Braille_RunLapAroundWall: @ 82A6CD4
	.braille "STAY CLOSE\n"
	.braille "TO THE WALL.\n"
	.braille "RUN AROUND\n"
	.braille "ONE LAP.$"

AncientTomb_Braille_ShineInTheMiddle: @ 82A6D06
	.braille "THOSE WHO\n"
	.braille "INHERIT OUR\n"
	.braille "WILL, SHINE\n"
	.braille "IN THE MIDDLE.$"
