gText_ObtainedTheItems::
	.string "Obtained {STR_VAR_1} {COLOR GREEN}{STR_VAR_2}{COLOR DARK_GRAY}!$"

gText_ObtainedTheItem::
	.string "Obtained the {COLOR GREEN}{STR_VAR_2}{COLOR DARK_GRAY}!$"

gText_TheBagIsFull::
	.string "The BAG is full…$"

gText_PutItemInPocket::
	.string "{PLAYER} put away the {STR_VAR_2}\n"
	.string "in the {STR_VAR_3} POCKET.$"

gText_PlayerFoundItems::
	.string "{PLAYER} found {STR_VAR_1} {COLOR GREEN}{STR_VAR_2}{COLOR DARK_GRAY}!$"

gText_PlayerFoundOneItem::
	.string "{PLAYER} found one {COLOR GREEN}{STR_VAR_2}{COLOR DARK_GRAY}!$"

gText_TooBadBagIsFull::
	.string "Too bad!\n"
	.string "The BAG is full…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} put away the {STR_VAR_2}\n"
	.string "in the BAG.$"

gText_NoRoomLeftForAnother::
	.string "Too bad! There's no room left for\n"
	.string "another {STR_VAR_2}…$"
