gText_NurseIntro_Morning:: @ 82726EB
    .string "Good morning, and welcome to the\n"
.if UK
    .string "POKéMON CENTRE.\p$"
.else
    .string "POKéMON CENTER.\p$"
.endif

gText_NurseIntro_Day:: @ 82726EB
    .string "Hello, and welcome to the POKéMON\n"
.if UK
    .string "CENTRE.\p$"
.else
    .string "CENTER.\p$"
.endif

gText_NurseIntro_Night:: @ 82726EB
    .string "Good evening, and welcome to the\n"
.if UK
    .string "POKéMON CENTRE.\p$"
.else
    .string "POKéMON CENTER.\p$"
.endif

gText_WouldYouLikeToRestYourPkmn:: @ 82726EB
    .string "We restore your tired POKéMON to\n"
    .string "full health.\p"
    .string "Would you like to rest your POKéMON?$"


gText_IllTakeYourPkmn:: @ 8272768
    .string "Okay, I'll take your POKéMON for a\n"
    .string "few seconds.$"

gText_RestoredPkmnToFullHealth:: @ 8272798
    .string "Thank you for waiting.\p"
    .string "We've restored your POKéMON to\n"
    .string "full health.$"

gText_WeHopeToSeeYouAgain:: @ 82727DB
    .string "We hope to see you again!$"

gText_WelcomeCutShort:: @ 82727F5
    .string "We restore your tired POKéMON to\n"
    .string "full health.\p"
    .string "Would you like to…$"

gText_NoticesGoldCard:: @ 8272860
    .string "Th-that card…\n"
    .string "Could it be… The GOLD CARD?!\p"
.if UK
    .string "Oh, the gold colour is brilliant!\n"
.else
    .string "Oh, the gold color is brilliant!\n"
.endif
    .string "The four stars seem to sparkle!\p"
    .string "I've seen several TRAINERS with\n"
    .string "a SILVER CARD before, but, {PLAYER},\l"
    .string "you're the first TRAINER I've ever\l"
    .string "seen with a GOLD CARD!\p"
    .string "Okay, {PLAYER}, please allow me\n"
.if UK
    .string "the honour of resting your POKéMON!$"
.else
    .string "the honor of resting your POKéMON!$"
.endif

gText_YouWantTheUsual:: @ 8272982
    .string "I'm delighted to see you, {PLAYER}!\n"
    .string "You want the usual, am I right?$"

gText_ThankYouForWaiting:: @ 82729F0
    .string "Thank you for waiting.$"
