gTVBravoTrainerText05::
	.string "Wouldn't you also like to know what\n"
	.string "{STR_VAR_1} imagines {STR_VAR_2} to be?\p"
	.string "You bet we did!\n"
	.string "So we asked, of course!\p"
	.string "The answer is all perfectly condensed:\n"
	.string "“{STR_VAR_3}!”\p"
	.string "That's what the concept of {STR_VAR_2}\n"
	.string "represents to {STR_VAR_1}!$"

gTVBravoTrainerText06::
	.string "The last move {STR_VAR_2} used by\n"
	.string "the {STR_VAR_1} is entirely about\l"
	.string "“{STR_VAR_3}”!$"

gTVBravoTrainerText07::
	.string "Bravo, {STR_VAR_1}!\n"
	.string "Bravo, {STR_VAR_2}!\p"
	.string "I hope we can count on seeing\n"
	.string "{STR_VAR_1} scale even greater heights!\p"
	.string "That's all the time we have!\n"
	.string "Until next time, see you!$"

gTVBravoTrainerText08::
	.string "Introducing the TRAINER's {STR_VAR_1}!$"

BattleFrontier_BattleTowerLobby_Text_InterviewRequest::
	.string "Hello! You're the TRAINER who just had\n"
	.string "a battle, right?\p"
	.string "I'm gathering interviews with TRAINERS\n"
	.string "all over the place.\p"
	.string "May I get a few words from you about\n"
	.string "your impressions on battling?$"

BattleFrontier_BattleTowerLobby_Text_HowDidBattleTowerTurnOut::
	.string "You will? Really?\n"
	.string "Thank you!\l"
	.string "Then, uh…\p"
	.string "How did things turn out in\n"
	.string "the BATTLE TOWER today?\p"
	.string "Were you satisfied with the battle?\n"
	.string "Or are you unhappy?$"

BattleFrontier_BattleTowerLobby_Text_SorryWeDisturbedYou::
	.string "Oh…\n"
	.string "Sorry we disturbed you.\p"
	.string "Please give us an interview the next\n"
	.string "time you visit the BATTLE TOWER.$"

BattleFrontier_BattleTowerLobby_Text_ObviousYouHadGreatBattle::
	.string "Well, of course!\p"
	.string "That unmistakable look of satisfaction\n"
	.string "on your face…\p"
	.string "It's obvious that you've had a great\n"
	.string "battle.$"

BattleFrontier_BattleTowerLobby_Text_DifficultToMakeBattleTurnOutAsPlanned::
	.string "Oh, I see…\p"
	.string "Well, it certainly is difficult to make a\n"
	.string "battle turn out exactly as planned.$"

BattleFrontier_BattleTowerLobby_Text_DescribeYourBattle::
	.string "Oh, oh, may I ask one more question?\p"
	.string "If you were to describe your\n"
	.string "impressions about this battle with\l"
	.string "one saying, what would it be?$"

BattleFrontier_BattleTowerLobby_Text_ThatsGreatLine::
	.string "Oh, that is stunningly cool!\p"
	.string "That's a great line!\n"
	.string "I hope you'll do great next time, too.\p"
	.string "I hope to see you again!$"

BattleFrontier_BattleTowerLobby_Text_SilentType::
	.string "Oh, I see…\p"
	.string "Still, being the silent type is also\n"
	.string "cool, isn't it?\p"
	.string "I hope you'll give me the opportunity\n"
	.string "to share your thoughts again!$"

BattleFrontier_BattleTowerLobby_Text_LookingForwardToNextBattle::
	.string "I'll be looking forward to your\n"
	.string "next battle!$"

gTVBravoTrainerBattleTowerText00::
	.string "Yeah!\n"
	.string "It's BRAVO TRAINER time!\p"
	.string "Today, we're going to profile {STR_VAR_1},\n"
	.string "who took the BATTLE TOWER challenge!\p"
	.string "For the challenge, {STR_VAR_1} entered\n"
	.string "one wicked {STR_VAR_2}.$"

gTVBravoTrainerBattleTowerText01::
	.string "The pair set a new record of {STR_VAR_2} wins\n"
	.string "in a row in {STR_VAR_1} competition!\l"
	.string "Bravo, TRAINER!$"

gTVBravoTrainerBattleTowerText02::
	.string "The twosome finally succumbed to\n"
	.string "{STR_VAR_1} in match number {STR_VAR_2}.\l"
	.string "Nice try, TRAINER!\p"
	.string "But, hey, it's just bad luck to run into\n"
	.string "{STR_VAR_1} so early in the challenge.\p"
	.string "We asked the TRAINER for impressions\n"
	.string "on the match with {STR_VAR_1}.$"

gTVBravoTrainerBattleTowerText03::
	.string "The twosome won it all by defeating\n"
	.string "{STR_VAR_1}'s {STR_VAR_2} thoroughly.\l"
	.string "Bravo, TRAINER!\p"
	.string "Knocking off even {STR_VAR_1}…\n"
	.string "It defies belief! Simply astounding!\p"
	.string "We asked the TRAINER for impressions\n"
	.string "on the moment of glory.$"

gTVBravoTrainerBattleTowerText04::
	.string "After a string of wins, the pair finally\n"
	.string "succumbed to {STR_VAR_1}'s {STR_VAR_2},\l"
	.string "their final hurdle.\p"
	.string "Nice try, TRAINER!\p"
	.string "Still, you have to give credit.\n"
	.string "You don't see many famous combinations\l"
	.string "like {STR_VAR_1} and {STR_VAR_2}.\p"
	.string "We asked the TRAINER for impressions\n"
	.string "on battling the celebrity pair.$"

gTVBravoTrainerBattleTowerText05::
	.string "This is what the TRAINER had to say:\n"
	.string "“I'm satisfied!”\p"
	.string "Now isn't that a refreshing reply?\n"
	.string "Bravo, TRAINER!\p"
	.string "Isn't it out-and-out awesome to be\n"
	.string "able to battle to full satisfaction?\p"
	.string "I found out exactly how satisfied\n"
	.string "when I heard the TRAINER say this:$"

gTVBravoTrainerBattleTowerText06::
	.string "This is what the TRAINER had to say:\n"
	.string "“I'm not satisfied…”\p"
	.string "Our TRAINER was obviously a little down\n"
	.string "when that was uttered.\p"
	.string "Still, it's not easy to be able to battle\n"
	.string "with complete satisfaction, am I right?\p"
	.string "Anyway, I found out how dissatisfied\n"
	.string "our TRAINER was when I heard this:$"

gTVBravoTrainerBattleTowerText07::
	.string "None$"

gTVBravoTrainerBattleTowerText11::
	.string "“{STR_VAR_1}.”$"

gTVBravoTrainerBattleTowerText12::
	.string "“{STR_VAR_1}.”\n"
	.string "Now isn't that great?\p"
	.string "It really expresses {STR_VAR_2}'s joy,\n"
	.string "I'd say.\p"
	.string "That battle with {STR_VAR_3} at the\n"
	.string "end… It really was what you'd call\l"
	.string "“{STR_VAR_1}”!$"

gTVBravoTrainerBattleTowerText13::
	.string "“{STR_VAR_1}.”\n"
	.string "Now isn't that fitting?\p"
	.string "That battle with {STR_VAR_3} at the\n"
	.string "end… You can't describe it as anything\l"
	.string "else but “{STR_VAR_1}”!\p"
	.string "{STR_VAR_2}'s disappointment comes across\n"
	.string "loud and clear, I'd say!$"

gTVBravoTrainerBattleTowerText14::
	.string "Bravo, {STR_VAR_1}!\n"
	.string "Bravo, {STR_VAR_2}!\p"
	.string "I hope we can count on seeing\n"
	.string "{STR_VAR_1} scale even greater heights!\p"
	.string "That's all the time we have!\n"
	.string "Until next time, see you!$"

SlateportCity_PokemonFanClub_Text_InterviewRequestHasName:
	.string "Wow!\p"
	.string "It's plain to see that you lavish your\n"
	.string "love on your {STR_VAR_1}.\p"
	.string "Okay, it's named {STR_VAR_2}.\p"
	.string "Can I ask you a favor?\p"
	.string "I'm a TV reporter, and I'm running\n"
	.string "a survey on POKéMON.\p"
	.string "Would you be willing to answer a few\n"
	.string "simple questions for me?$"

SlateportCity_PokemonFanClub_Text_HereGoesQuickAnswers:
	.string "Great! Thank you!\p"
	.string "Okay, here goes.\n"
	.string "I just need quick answers, okay?$"

SlateportCity_PokemonFanClub_Text_DescribeFeelingsFirstMetMon:
	.string "When you first met {STR_VAR_1},\n"
	.string "what did you feel?\p"
	.string "How would you describe your feelings\n"
	.string "at the time?$"

SlateportCity_PokemonFanClub_Text_LikenMonToSomethingYouLike:
	.string "Your {STR_VAR_1} is cared for lovingly.\p"
	.string "If you were to liken it to something\n"
	.string "that you like, what would it be?$"

SlateportCity_PokemonFanClub_Text_WhatAttractedYouAboutMon:
	.string "This question also relates to your\n"
	.string "beloved {STR_VAR_1}.\p"
	.string "What was it about {STR_VAR_1} that\n"
	.string "attracted you?$"

SlateportCity_PokemonFanClub_Text_WhatDoPokemonMeanToYou:
	.string "Okay, that makes sense.\p"
	.string "The next question might be a little\n"
	.string "on the tough side.\p"
	.string "Here goes…\p"
	.string "What do POKéMON mean to you?$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview:
	.string "I see!\p"
	.string "Hmhm…\p"
	.string "Okay!\n"
	.string "Thanks for helping me out.\p"
	.string "It was fun and enlightening\n"
	.string "chatting with you.\p"
	.string "It's possible that our interview will\n"
	.string "end up on TV. Tune in and check!\p"
	.string "Okay, that's all.\n"
	.string "Bye-bye!$"

SlateportCity_PokemonFanClub_Text_HereIfYouGetUrgeToTellMe:
	.string "Oh, okay…\p"
	.string "Well, if you get the urge to tell me\n"
	.string "about POKéMON, I'll be here!$"

SlateportCity_PokemonFanClub_Text_EnjoyDoingInterviews:
	.string "I enjoy this job--you get to learn\n"
	.string "about POKéMON by doing interviews.$"

SlateportCity_PokemonFanClub_Text_InterviewRequest:
	.string "Hi, you seem to be very close to your\n"
	.string "{STR_VAR_1}.\p"
	.string "Do you know what?\n"
	.string "I'm a TV reporter.\p"
	.string "I travel around interviewing people\n"
	.string "about POKéMON.\p"
	.string "I'm wondering if you'd be willing to tell\n"
	.string "me a little about your {STR_VAR_1}?$"

SlateportCity_PokemonFanClub_Text_TellMeAnythingAboutYourMon:
	.string "Wow, thank you!\p"
	.string "Okay, then, please tell me anything\n"
	.string "you'd like about your {STR_VAR_1}.$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview2:
	.string "Wow…\n"
	.string "That's an interesting account.\p"
	.string "You really are tight with {STR_VAR_1},\n"
	.string "aren't you?\p"
	.string "I get the feeling that your account\n"
	.string "will make a great TV story.\p"
	.string "I promise that I'll turn this into\n"
	.string "an entertaining show.\l"
	.string "Keep your eyes out for it.\p"
	.string "Okay, that's all.\n"
	.string "Bye-bye!$"

gTVFanClubOpinionsText00::
	.string "WE ARE THE POKéMON FAN CLUB!\p"
	.string "We're on the air!\p"
	.string "On this program, we get your opinions,\n"
	.string "and I shout them out on your behalf!\l"
	.string "Isn't it a fantastic program concept?\p"
	.string "Today, we bring you this report from\n"
	.string "our reporter, who we sent out to the\l"
	.string "POKéMON FAN CLUB.\p"
	.string "So, just who is today's featured\n"
	.string "POKéMON fan?\p"
	.string "… … … … … … … …\p"
	.string "{STR_VAR_1}!\p"
	.string "So, let's hear what {STR_VAR_1} has to\n"
	.string "say about {STR_VAR_3} the {STR_VAR_2}.\p"
	.string "And, I will shout those words of love\n"
	.string "out loud on TV!\p"
	.string "Hoo-hah!\p"
	.string "Let's shout!$"

gTVFanClubOpinionsText01::
	.string "We asked {STR_VAR_1}, “When you first\n"
	.string "laid eyes on your {STR_VAR_2}, what was\l"
	.string "your initial thought?”\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Yeahah! That's a mighty fine shout!\p"
	.string "Doesn't it bring back memories of those\n"
	.string "days long gone by?$"

gTVFanClubOpinionsText02::
	.string "We asked {STR_VAR_1}, “If you were to\n"
	.string "liken your {STR_VAR_2} to something,\l"
	.string "it would be…”\p"
	.string "… … … … … … … …\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Whoah-oh, now that's an original idea!\p"
	.string "You sure can sense the intensity of\n"
	.string "feeling the TRAINER has for\l"
	.string "{STR_VAR_2}.$"

gTVFanClubOpinionsText03::
	.string "And let's see…\n"
	.string "What was it about that {STR_VAR_2}\l"
	.string "that so attracted {STR_VAR_1}?\p"
	.string "… … … … … … … …\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Whoa! Such a spectacular declaration!\p"
	.string "The TRAINER's love for the {STR_VAR_2}\n"
	.string "comes across loud and clear!$"

gTVFanClubOpinionsText04::
	.string "Hm? Oh, there's still more.\n"
	.string "Let's check it out!\p"
	.string "Let me see, now…\p"
	.string "We asked {STR_VAR_1}, “What do POKéMON\n"
	.string "mean to you?”\p"
	.string "… … … … … …\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Bravo!\p"
	.string "That's the best shout I've had all day!\p"
	.string "“{STR_VAR_3}!”\p"
	.string "It makes you want to shout it out loud\n"
	.string "again and again!\p"
	.string "Now that we've had a great shout, it's\n"
	.string "time to say good-bye until next time!\p"
	.string "So, let's all have one last shout!\n"
	.string "All together now…\p"
	.string "“{STR_VAR_3}!”$"

gTVFanClubText00::
	.string "WE ARE THE POKéMON FAN CLUB!\p"
	.string "We're on the air!\p"
	.string "Today, we'll get rolling with the\n"
	.string "POKéMON SURVEY CORNER.\p"
	.string "Out of all the tales woven by POKéMON\n"
	.string "and TRAINERS, what startling new drama\l"
	.string "will grab our attention today?\p"
	.string "Let me see…\p"
	.string "This one!\p"
	.string "We'll start with this letter!\p"
	.string "It's a letter from {STR_VAR_1} about a\n"
	.string "beloved {STR_VAR_2}.\p"
	.string "Let's see how passionately our writer\n"
	.string "can express love for the {STR_VAR_2}!\l"
	.string "Hmhm…$"

gTVFanClubText01::
	.string "Whoah!\n"
	.string "What an amazing letter!$"

gTVFanClubText02::
	.string "I loved it, so here it is again!$"

gTVFanClubText03::
	.string "A great letter bears reading over\n"
	.string "and over!$"

gTVFanClubText04::
	.string "The bit “{STR_VAR_3},” that really\n"
	.string "accentuates emotional impact!\p"
	.string "It's a great letter that has real\n"
	.string "heartfelt depth!$"

gTVFanClubText05::
	.string "Especially that “{STR_VAR_3}” bit!\p"
	.string "I love how “{STR_VAR_3}” is used!$"

gTVFanClubText06::
	.string "By the way, and it's not important,\n"
	.string "but “{STR_VAR_3}” is a great saying.\p"
	.string "I've been using “{STR_VAR_3}” a lot\n"
	.string "in conversations lately.$"

gTVFanClubText07::
	.string "If I had to score this letter,\n"
	.string "I'd give it {STR_VAR_3} points.\p"
	.string "Next time, I'll be expecting an even\n"
	.string "better letter, {STR_VAR_1}!\p"
	.string "A-whoops, will you look at the time?\n"
	.string "Time to say good-bye until next time!$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequest:
	.string "Oh?\n"
	.string "Do you perhaps like POKéMON?\p"
	.string "I'm on assignment with the TV network.\p"
	.string "I'm gathering stories on POKéMON and\n"
	.string "TRAINERS that occurred recently.\p"
	.string "If you don't mind, could you tell me\n"
	.string "something about yourself?$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequestShort:
	.string "I'm gathering stories on POKéMON and\n"
	.string "TRAINERS that occurred recently.\p"
	.string "If you don't mind, could you tell me\n"
	.string "something about yourself?$"

SlateportCity_OceanicMuseum_1F_Text_TellMeExperienceInvolvingPokemon:
	.string "Oh, you will?\n"
	.string "Thank you!\p"
	.string "Then, please, tell me anything of\n"
	.string "interest that you experienced recently\l"
	.string "involving POKéMON.$"

SlateportCity_OceanicMuseum_1F_Text_LetMeKnowIfYouHaveStory:
	.string "Oh, I see…\p"
	.string "Well, if you do have an interesting\n"
	.string "story to tell, please let me know.$"

SlateportCity_OceanicMuseum_1F_Text_ThatsAllForInterview:
	.string "Oh, what an uplifting story!\p"
	.string "I'll be sure to get your story told\n"
	.string "on television.\p"
	.string "It should be aired sometime, I think,\n"
	.string "so please look forward to it.$"

SlateportCity_OceanicMuseum_1F_Text_BetterWriteUpStory:
	.string "Hmmm…\n"
	.string "I've got a good story for a TV program.\p"
	.string "I'd better write it up in a hurry!$"

gTVRecentHappeningsText00::
	.string "Hello, it's time for RECENT HAPPENINGS.\p"
	.string "For POKéMON TRAINERS, every day\n"
	.string "is a storybook tale.\p"
	.string "What we want to do is to introduce you\n"
	.string "to some of these POKéMON tales.\p"
	.string "Today, we bring you the story\n"
	.string "of the TRAINER {STR_VAR_1}.\p"
	.string "What did {STR_VAR_1} experience recently?\n"
	.string "Let's find out.\p"
	.string "Let's see…$"

gTVRecentHappeningsText01::
	.string "Wasn't that enlightening?\p"
	.string "The story gives you a clear idea of what\n"
	.string "{STR_VAR_1} has experienced recently.\l"
	.string "It's as if we were there as witnesses!$"

gTVRecentHappeningsText02::
	.string "“{STR_VAR_3}.” That\n"
	.string "accents the tale and gives it depth.$"

gTVRecentHappeningsText03::
	.string "“{STR_VAR_3}.”\n"
	.string "That gives the tale a sense of place.\l"
	.string "It lets us envision the tale's setting.$"

gTVRecentHappeningsText04::
	.string "The “{STR_VAR_3}”\n"
	.string "section of the tale is very expressive.$"

gTVRecentHappeningsText05::
	.string "{STR_VAR_1} has recounted a wonderful\n"
	.string "tale involving POKéMON.\p"
	.string "And now {STR_VAR_1}'s tale is indelibly\n"
	.string "etched into your soul, too.\p"
	.string "That's it for today.\n"
	.string "Please tune in next time.$"

gTVMassOutbreakText00::
	.string "Greetings!\n"
	.string "It's time for POKéMON NEWS.\p"
	.string "We've just received word of a very\n"
	.string "rare occurrence.\p"
	.string "There have been reports of a mass\n"
	.string "outbreak of {STR_VAR_2} in the vicinity\l"
	.string "of {STR_VAR_1}.\p"
	.string "{STR_VAR_2}, as you're probably aware,\n"
	.string "is known as a POKéMON that's rare\l"
	.string "and hard to find.\p"
	.string "It sounds like a rare opportunity to\n"
	.string "see the mystifying outbreak of\l"
	.string "{STR_VAR_2} in the wild.\p"
	.string "That's the news on POKéMON NEWS.$"

gTV3CheersForPokeblocksText00::
	.string "MC: We hope you're in good cheer,\n"
	.string "“3 CHEERS FOR {POKEBLOCK}S” is here!\p"
	.string "Today, we examine the {POKEBLOCK} blended\n"
	.string "by {STR_VAR_1} and associates.\p"
	.string "Without any delay, let me feed it\n"
	.string "to my gourmet POKéMON GULPIN.\p"
	.string "… … … … … …\n"
	.string "… … … … … …$"

gTV3CheersForPokeblocksText01::
	.string "GULPIN: Gubi! Gubii!\p"
	.string "MC: And the verdict is very {STR_VAR_1}!\n"
	.string "GULPIN says it tastes “{STR_VAR_2}!”\p"
	.string "Thank you so much, {STR_VAR_3}!$"

gTV3CheersForPokeblocksText02::
	.string "{STR_VAR_1}'s blending performance\n"
	.string "left something to be desired.\p"
	.string "If this TRAINER could blend better,\n"
	.string "the {POKEBLOCK} would be much tastier.$"

gTV3CheersForPokeblocksText03::
	.string "GULPIN: Gubi! Gubii!\p"
	.string "MC: Hmm… It's too {STR_VAR_1}.\n"
	.string "GULPIN says it tastes “{STR_VAR_2}!”\p"
	.string "It looks like {STR_VAR_3}'s errors\n"
	.string "hurt the blending quality…$"

gTV3CheersForPokeblocksText04::
	.string "It's too bad that {STR_VAR_1}'s\n"
	.string "leading effort went to waste.\p"
	.string "Let's hope {STR_VAR_2} can turn in\n"
	.string "a better showing next time!$"

gTV3CheersForPokeblocksText05::
	.string "Tune in next time!\n"
	.string "Our slogan is “3 CHEERS FOR {POKEBLOCK}S!”$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer::
	.string "Hi, there!\p"
	.string "I'm a big fan of {STR_VAR_1}.\n"
	.string "What's your opinion of {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_ThatsWhatYouThink::
	.string "I see, I see. That's what you think\n"
	.string "about the TRAINER.$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer::
	.string "Have you completely forgotten\n"
	.string "about {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer2::
	.string "I'm a big fan of {STR_VAR_1}.\n"
	.string "What's your opinion of {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_HowStrongRateTrainer::
	.string "How strong would you rate {STR_VAR_1}\n"
	.string "on a scale of one hundred?$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer2::
	.string "Have you completely forgotten\n"
	.string "about {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_YouShouldMeetTrainer::
	.string "Oh, I see!\n"
	.string "You should meet {STR_VAR_1} sometime.\l"
	.string "I'm sure you'll become a fan, too!$"

LilycoveCity_PokemonTrainerFanClub_Text_ThankYouIllShareThisInfo::
	.string "I see, I see.\p"
	.string "Thank you!\n"
	.string "That's very useful to know.\p"
	.string "I'll share this information with other\n"
	.string "{STR_VAR_1} fans and discuss it.$"

LilycoveCity_PokemonTrainerFanClub_HopeYouCatchTVSpecial::
	.string "There's going to be a TV special on\n"
	.string "{STR_VAR_1} very soon.\p"
	.string "I hope you catch it!$"

gTVTrainerFanClubSpecialText00::
	.string "TRAINER FAN CLUB\n"
	.string "{STR_VAR_1} SPECIAL!\p"
	.string "This is a special presentation for\n"
	.string "the fans of {STR_VAR_1} all over HOENN!\p"
	.string "Today, we ask the question, “What do\n"
	.string "people think of {STR_VAR_1}?”\p"
	.string "We posed the question to {STR_VAR_2}\n"
	.string "as the TRAINER representative.\p"
	.string "We asked, “In one word, how would\n"
	.string "you describe {STR_VAR_1}?”\p"
	.string "The reply: “{STR_VAR_3}.”\p"
	.string "Kudos to {STR_VAR_2}!\n"
	.string "What a perceptive opinion!\p"
	.string "“{STR_VAR_3} {STR_VAR_1}.”\n"
	.string "It has such a nice ring to it!\p"
	.string "{STR_VAR_2} also scored {STR_VAR_1}'s\n"
	.string "strength from 0 to 100.$"

gTVTrainerFanClubSpecialText01::
	.string "The score was {STR_VAR_3} points!\n"
	.string "That is a very high score indeed!\p"
	.string "{STR_VAR_2} must obviously hold\n"
	.string "{STR_VAR_1} in very high esteem.$"

gTVTrainerFanClubSpecialText02::
	.string "The score was {STR_VAR_3} points!\n"
	.string "That is quite a good score.\p"
	.string "{STR_VAR_2} must consider\n"
	.string "{STR_VAR_1} to be a rival.$"

gTVTrainerFanClubSpecialText03::
	.string "The score was {STR_VAR_3} points!\n"
	.string "That's a rather weak score.\p"
	.string "{STR_VAR_2} must consider\n"
	.string "{STR_VAR_1} to be a mere sidekick.$"

gTVTrainerFanClubSpecialText04::
	.string "The score was {STR_VAR_3} point(s)!\n"
	.string "That's a terrible score.\p"
	.string "{STR_VAR_2} must consider\n"
	.string "{STR_VAR_1} to be an underling.$"

gTVTrainerFanClubSpecialText05::
	.string "There you have it, folks!\p"
	.string "I think we all learned something\n"
	.string "new about {STR_VAR_1}.\p"
	.string "In closing, I'll leave you with\n"
	.string "{STR_VAR_2}'s words.\p"
	.string "{STR_VAR_3} {STR_VAR_1}!$"

gTVNameRaterText00::
	.string "And now, it's time for…\n"
	.string "THE NAME RATER SHOW.\p"
	.string "I tell your POKéMON's fortune from\n"
	.string "the nickname you've bestowed.\p"
	.string "Advice is what I have to give, and it is\n"
	.string "helpful advice that I offer.\p"
	.string "Today, I shall do a reading of\n"
	.string "the nickname {STR_VAR_3} of {STR_VAR_1}'s\l"
	.string "POKéMON {STR_VAR_2}.\p"
	.string "Hmhm…\p"
	.string "Hmm…\n"
	.string "This nickname is…$"

gTVNameRaterText01::
	.string "A nickname that hints at talent in many\n"
	.string "different ways.\p"
	.string "I urge this TRAINER to take courage\n"
	.string "and take on many challenges.$"

gTVNameRaterText02::
	.string "A nickname that perfectly complements\n"
	.string "{STR_VAR_1}, the TRAINER's name.\p"
	.string "It suggests that you will forge a fine\n"
	.string "partnership with precise timing.$"

gTVNameRaterText03::
	.string "A nickname fit for a unique individual\n"
	.string "of a POKéMON!\p"
	.string "If raised properly, this POKéMON's\n"
	.string "uniqueness will bloom excessively!$"

gTVNameRaterText04::
	.string "A nickname that will nurture the caring\n"
	.string "and compassionate side of POKéMON.\p"
	.string "If raised properly, this POKéMON will\n"
	.string "come to exhibit real warmth!$"

gTVNameRaterText05::
	.string "A very fine nickname that hints at\n"
	.string "greatness to come.\p"
	.string "I am intrigued about what the future\n"
	.string "holds in store for this POKéMON.$"

gTVNameRaterText06::
	.string "A good nickname that should make the\n"
	.string "POKéMON hale and hearty!\p"
	.string "That POKéMON should remain fit and\n"
	.string "robust for a long, long time.$"

gTVNameRaterText07::
	.string "A good nickname that should make the\n"
	.string "POKéMON very active!\p"
	.string "I should think that this POKéMON will be\n"
	.string "a strong performer in battles.$"

gTVNameRaterText08::
	.string "An appealing nickname that should make\n"
	.string "the POKéMON very charming!\p"
	.string "I don't doubt that this POKéMON will be\n"
	.string "quite the charmer in POKéMON CONTESTS.$"

gTVNameRaterText09::
	.string "The nickname {STR_VAR_1} is rooted by\n"
	.string "the letter “{STR_VAR_3}.”\p"
	.string "That letter is supported by the first\n"
	.string "letter “{STR_VAR_2},” which gives it a solid sense\l"
	.string "of presence as a nickname.$"

gTVNameRaterText10::
	.string "The nickname {STR_VAR_1} is very\n"
	.string "shapely in a pleasing manner.\p"
	.string "The presence of the letters “{STR_VAR_2}” and\n"
	.string "“{STR_VAR_3}”--now that is remarkably good!$"

gTVNameRaterText11::
	.string "The nickname {STR_VAR_1}--it has a\n"
	.string "sublime, flowing feel to it.\p"
	.string "The flow from the initial letter “{STR_VAR_2}” to\n"
	.string "“{STR_VAR_3}” is especially wonderful.$"

gTVNameRaterText12::
	.string "Let's examine other examples of fine\n"
	.string "nicknames, shall we?$"

gTVNameRaterText13::
	.string "Try this example. Take a part of the\n"
	.string "TRAINER name of {STR_VAR_1}, and end\l"
	.string "up with the fine nickname {STR_VAR_2}{STR_VAR_3}.$"

gTVNameRaterText14::
	.string "The nickname {STR_VAR_2}{STR_VAR_3} would also work\n"
	.string "quite well.$"

gTVNameRaterText15::
	.string "The POKéMON's species name of\n"
	.string "{STR_VAR_2} could be used as the basis\l"
	.string "for making the nickname {STR_VAR_1}{STR_VAR_3}.$"

gTVNameRaterText16::
	.string "{STR_VAR_1}{STR_VAR_3} would also be an effective\n"
	.string "nickname.$"

gTVNameRaterText17::
	.string "What should always be avoided is using\n"
	.string "another POKéMON species name.\p"
	.string "For instance, avoid taking the name of\n"
	.string "{STR_VAR_2} to make the nickname {STR_VAR_1}{STR_VAR_3}.\l"
	.string "That is unacceptable.$"

gTVNameRaterText18::
	.string "I must say that {STR_VAR_1} is quite\n"
	.string "a good nickname.\p"
	.string "I hope that the TRAINER will continue\n"
	.string "to treat {STR_VAR_1} with love.\p"
	.string "That's it for today's show.\n"
	.string "May we meet again.$"

gTVPokemonAnglerText00::
	.string "{STR_VAR_2} ANGLER\p"
	.string "ANNOUNCER: Hello! Today, we'll get tips\n"
	.string "on fishing for {STR_VAR_2}.\p"
	.string "GURU, what advice can you give for\n"
	.string "catching {STR_VAR_2}?\p"
	.string "GURU: Hm? Catching {STR_VAR_2}?\n"
	.string "Well, let me tell you, be patient and\l"
	.string "wait. That's the bottom line.\p"
	.string "Do you see {STR_VAR_1} over there?\n"
	.string "That TRAINER makes a good example.\p"
	.string "That TRAINER's already had\n"
	.string "{STR_VAR_3} POKéMON get away.\p"
	.string "But there {STR_VAR_1} waits. No giving up.\n"
	.string "That's the law for catching {STR_VAR_2}.\p"
	.string "ANNOUNCER: I see…\p"
	.string "Oh! {STR_VAR_1} has finally landed an\n"
	.string "elusive {STR_VAR_2}!\p"
	.string "The TRAINER appears close to tears\n"
	.string "out of sheer joy!\p"
	.string "Seeing that elated look, I'm getting\n"
	.string "the itch to go fishing, too!\p"
	.string "Viewers, why not take this as a cue to\n"
	.string "try some {STR_VAR_2} fishing?\p"
	.string "Until our next broadcast, farewell and\n"
	.string "good fishing to you all!$"

gTVPokemonAnglerText01::
	.string "{STR_VAR_2} ANGLER\p"
	.string "ANNOUNCER: Hello! Today, we'll get tips\n"
	.string "on fishing for {STR_VAR_2}.\p"
	.string "GURU, what advice can you give for\n"
	.string "catching {STR_VAR_2}?\p"
	.string "GURU: Hm? Catching {STR_VAR_2}?\n"
	.string "Well, let me tell you, use your fishing\l"
	.string "ROD with vigor!\p"
	.string "Do you see {STR_VAR_1} over there?\n"
	.string "See how the ROD is handled?\p"
	.string "That TRAINER's already caught\n"
	.string "{STR_VAR_3} in a row.\p"
	.string "ANNOUNCER: It's incredible!\n"
	.string "It looks like a storm…\p"
	.string "Seeing technique of that caliber, I'm\n"
	.string "getting the itch to go fishing, too.\p"
	.string "Viewers, why not take this as a cue to\n"
	.string "try some {STR_VAR_2} fishing?\p"
	.string "Until our next broadcast, farewell and\n"
	.string "good fishing to you all!$"

gTVPokemonTodayFailedText00::
	.string "Hello!\p"
	.string "It's time for POKéMON TODAY!\p"
	.string "BIG SIS: Hi! Is everyone peachy and\n"
	.string "perky today?\p"
	.string "Today, we're going to look at {STR_VAR_1}'s\n"
	.string "POKéMON {STR_VAR_2}!\p"
	.string "BIG BRO: Yeah! That's what we're going\n"
	.string "to do!$"

gTVPokemonTodayFailedText01::
	.string "Oh!\n"
	.string "Speaking of {STR_VAR_1}…\p"
	.string "BIG SIS, I saw the TRAINER with my very\n"
	.string "own eyes!\p"
	.string "BIG SIS: Oh, what did you see?\p"
	.string "BIG BRO: Well, I had to go on a trip to\n"
	.string "{STR_VAR_2}.\p"
	.string "That's when I happened to come across\n"
	.string "{STR_VAR_1}, who was trying to catch the\l"
	.string "POKéMON {STR_VAR_3}, but…$"

gTVPokemonTodayFailedText02::
	.string "The POKéMON managed to get away!\p"
	.string "It ended up wasting this many\n"
	.string "POKé BALLS: {STR_VAR_2}!\p"
	.string "You should have seen the expression\n"
	.string "of frustration on {STR_VAR_1}'s face when\l"
	.string "the POKéMON took off!$"

gTVPokemonTodayFailedText03::
	.string "But {STR_VAR_1} goofed and made the\n"
	.string "POKéMON faint!\p"
	.string "It ended up wasting this many\n"
	.string "POKé BALLS: {STR_VAR_2}!\p"
	.string "You should have seen the expression\n"
	.string "of stunned dismay on {STR_VAR_1}'s face\l"
	.string "when the POKéMON fainted!$"

gTVPokemonTodayFailedText04::
	.string "BIG SIS: Hey, there!\n"
	.string "That's not nice!\p"
	.string "You shouldn't be laughing at other\n"
	.string "people's misfortune!\p"
	.string "Oh, poor {STR_VAR_1}.\n"
	.string "What a shame!\p"
	.string "BIG BRO: That's true!\n"
	.string "Sorry for laughing.$"

gTVPokemonTodayFailedText05::
	.string "BIG SIS: Bufufu…\p"
	.string "BIG BRO: Hey!\n"
	.string "You just laughed, too!\p"
	.string "BIG SIS: Huh?!\p"
	.string "I didn't laugh!\n"
	.string "Honestly, I didn't!\p"
	.string "Oh, poor {STR_VAR_1}.\n"
	.string "What a shame!\p"
	.string "BIG BRO: …$"

gTVPokemonTodayFailedText06::
	.string "BIG SIS: That's enough silliness!\n"
	.string "Let's look at today's POKéMON…\p"
	.string "Huh?\n"
	.string "We're out of time already?\p"
	.string "Aww!\n"
	.string "We couldn't profile a POKéMON today!\p"
	.string "BIG BRO: See you again next time!\p"
	.string "BIG SIS: Hey, don't end the show\n"
	.string "without me!$"

gTVPokemonTodaySuccessfulText00::
	.string "Hello!\p"
	.string "It's time for POKéMON TODAY!\p"
	.string "BIG SIS: Hi! Is everyone peachy and\n"
	.string "perky today?\p"
	.string "Today, we're going to look at {STR_VAR_1}'s\n"
	.string "POKéMON {STR_VAR_2}!\p"
	.string "BIG BRO: Yeah! That's what we're going\n"
	.string "to do!$"

gTVPokemonTodaySuccessfulText01::
	.string "BIG SIS: {STR_VAR_1} gave the nickname\n"
	.string "{STR_VAR_3} to the {STR_VAR_2}!\p"
	.string "It sounds like {STR_VAR_3} is getting\n"
	.string "good, loving care!$"

gTVPokemonTodaySuccessfulText02::
	.string "BIG BRO: The TRAINER had to throw this\n"
	.string "many POKé BALLS to catch it: {STR_VAR_3}!\p"
	.string "It finally took a single {STR_VAR_2}\n"
	.string "to catch it!$"

gTVPokemonTodaySuccessfulText03::
	.string "BIG SIS: If it was that easy to catch,\n"
	.string "it must have been destiny that brought\l"
	.string "{STR_VAR_1} and the {STR_VAR_2} together!$"

gTVPokemonTodaySuccessfulText04::
	.string "BIG SIS: Wow! That's so neat!\p"
	.string "But you know what they say, a POKéMON\n"
	.string "that takes a lot of effort to catch\l"
	.string "earns the love of its TRAINER!$"

gTVPokemonTodaySuccessfulText05::
	.string "BIG SIS: {STR_VAR_1}'s {STR_VAR_2} is a\n"
	.string "memorable POKéMON because it took an\l"
	.string "invaluable MASTER BALL to catch!\p"
	.string "BIG BRO: Wow! That's mega-awesome!\p"
	.string "BIG SIS: {STR_VAR_1} must have really\n"
	.string "wanted that {STR_VAR_2}, for sure!$"

gTVPokemonTodaySuccessfulText06::
	.string "BIG BRO: Then to give the nickname\n"
	.string "{STR_VAR_3} to that {STR_VAR_2}…\p"
	.string "You really get a good idea about\n"
	.string "{STR_VAR_1}'s TRAINER sense.\p"
	.string "BIG SIS: I second that notion!$"

gTVPokemonTodaySuccessfulText07::
	.string "If it were me, I'd give that nickname\n"
	.string "to something like this {STR_VAR_3}!\p"
	.string "BIG BRO: Whoa! That could be the start\n"
	.string "of something new!$"

gTVPokemonTodaySuccessfulText08::
	.string "{STR_VAR_2} the {STR_VAR_1}?\n"
	.string "Doesn't that sound perfect?\p"
	.string "The letters and everything--they\n"
	.string "sound just right for the POKéMON\l"
	.string "{STR_VAR_1}!\p"
	.string "BIG BRO: Yeah, true, that!$"

gTVPokemonTodaySuccessfulText09::
	.string "As far as I know, no TRAINER has ever\n"
	.string "given the nickname {STR_VAR_2} to their\l"
	.string "{STR_VAR_1}!\p"
	.string "BIG BRO: That just goes to show what\n"
	.string "great taste the TRAINER has in picking\l"
	.string "nicknames!$"

gTVPokemonTodaySuccessfulText10::
	.string "The next time I catch a POKéMON,\n"
	.string "I should give it the name {STR_VAR_2}.\p"
	.string "BIG BRO: Huh? Me, too!\n"
	.string "I'll use the nickname {STR_VAR_2}, too!$"

gTVPokemonTodaySuccessfulText11::
	.string "BIG SIS: Oh, no!\n"
	.string "Look at the time!\p"
	.string "Well, gang, this is it for today.\n"
	.string "See you again next time!\p"
	.string "BIG BRO: Remember, it could be your\n"
	.string "POKéMON in the spotlight next time!$"

SmartShopper_Text_Intro::
	.string "Hello!\p"
	.string "It's time for TODAY'S SMART SHOPPER.\p"
	.string "INTERVIEWER: How are you, viewers?\p"
	.string "Today we're visiting a shop\n"
	.string "in {STR_VAR_2}.\p"
	.string "Let's check on what the hot sellers\n"
	.string "have been recently.$"

SmartShopper_Text_ClerkNormal::
	.string "Let's interview the clerk to get the\n"
	.string "lowdown.\p"
	.string "Hi, how's your business?\p"
	.string "CLERK: Oh, we're doing excellent.\p"
	.string "Recently, {STR_VAR_2} has been\n"
	.string "selling especially strongly.\p"
	.string "Why, just the other day a TRAINER\n"
	.string "named {STR_VAR_1} bought {STR_VAR_3}.$"

SmartShopper_Text_RandomComment1::
	.string "INTERVIEWER: The TRAINER bought\n"
	.string "{STR_VAR_3} {STR_VAR_2}S? That's a haul!\p"
	.string "If I may say so, {STR_VAR_1} must have\n"
	.string "been stocking up for a long journey\l"
	.string "to far-off places.\p"
	.string "For traveling, {STR_VAR_2}S are so\n"
	.string "important!$"

SmartShopper_Text_RandomComment2::
	.string "INTERVIEWER: Speaking of the item\n"
	.string "{STR_VAR_2}, I just bought {STR_VAR_3} of\l"
	.string "them recently.\p"
	.string "After all, {STR_VAR_2}'s a great item!$"

SmartShopper_Text_RandomComment3::
	.string "INTERVIEWER: {STR_VAR_2}?!\n"
	.string "But {STR_VAR_3} of them?!\p"
	.string "I didn't think there would be anyone\n"
	.string "buying that many.\p"
	.string "My goodness, I can only afford one or\n"
	.string "two at a time…$"

SmartShopper_Text_RandomComment4::
	.string "INTERVIEWER: One time, I bought\n"
	.string "a whole lot of the item {STR_VAR_2}.\p"
	.string "But it turned out to be too many.\n"
	.string "I ended up regretting it…\p"
	.string "Since then, I only buy strictly what\n"
	.string "I absolutely need…\p"
	.string "Oops!\p"
	.string "There's no point talking about me!$"

SmartShopper_Text_SecondItem::
	.string "CLERK: {STR_VAR_1} also bought the item\n"
	.string "{STR_VAR_2} in bulk, taking {STR_VAR_3}.\p"
	.string "INTERVIEWER: Oh, that's smart.\n"
	.string "{STR_VAR_2}'s a very good item, too.$"

SmartShopper_Text_ThirdItem::
	.string "CLERK: And, the TRAINER also bought\n"
	.string "{STR_VAR_3} of the item {STR_VAR_2}.$"

SmartShopper_Text_DuringSale::
	.string "CLERK: Plus, it was during a big sale.\n"
	.string "That's smart shopping.$"

SmartShopper_Text_OutroNormal::
	.string "INTERVIEWER: Hmm… {STR_VAR_1} sounds like\n"
	.string "quite the shrewd bargain hunter!\p"
	.string "In total, {STR_VAR_1}'s purchases came to…\p"
	.string "¥{STR_VAR_2}?!\n"
	.string "What an amazing sum!\p"
	.string "Oops! We're out of time!\n"
	.string "See you on our next broadcast!$"

SmartShopper_Text_IsVIP::
	.string "CLERK: {STR_VAR_1} is a VIP customer,\n"
	.string "no doubt about it.$"

SmartShopper_Text_ClerkMax::
	.string "Let's interview the clerk to get the\n"
	.string "lowdown.\p"
	.string "Hi, how's your business?\p"
	.string "CLERK: Oh, we're doing unbelievable\n"
	.string "business. It's almost overwhelming.\p"
	.string "Recently, a TRAINER named {STR_VAR_1}\n"
	.string "bought the item {STR_VAR_2} in bulk.\p"
	.string "The TRAINER almost cleared out our\n"
	.string "entire stock of {STR_VAR_2}S.\p"
	.string "I never dreamt that any customer\n"
	.string "would ever need so many {STR_VAR_2}S.\l"
	.string "It's just unheard of!\p"
	.string "INTERVIEWER: So that would be like 100\n"
	.string "or 200 sold?\p"
	.string "CLERK: Oh, no, much more than that!\p"
	.string "INTERVIEWER: Oh, my goodness!\n"
	.string "{STR_VAR_1} must be a special shopper!\p"
	.string "CLERK: {STR_VAR_1} is a VIP customer,\n"
	.string "no doubt about it.$"

SmartShopper_Text_OutroMax::
	.string "INTERVIEWER: Hmm…\n"
	.string "That is amazing.\p"
	.string "But why would the TRAINER need to buy\n"
	.string "so many?\p"
	.string "… …\p"
	.string "The mystery deepens, but this is all\n"
	.string "the time we have today.\l"
	.string "See you on our next broadcast!\p"
	.string "Still, {STR_VAR_1} is certainly an enigma…$"

gTVWorldOfMastersText00::
	.string "THE WORLD OF MASTERS\p"
	.string "Hello, viewers.\p"
	.string "Perhaps you are aware of a TRAINER\n"
	.string "named {STR_VAR_1}.\p"
	.string "{STR_VAR_1} is famous as a master at\n"
	.string "catching POKéMON.\p"
	.string "{STR_VAR_1}'s quest for POKéMON depends\n"
	.string "entirely on a careful search on foot.\p"
	.string "On one memorable day, the TRAINER\n"
	.string "walked some {STR_VAR_2} steps.\p"
	.string "The total number of POKéMON caught\n"
	.string "that day reached an impressive {STR_VAR_3}!$"

gTVWorldOfMastersText01::
	.string "That remarkable feat must have been\n"
	.string "possible because of the trust between\l"
	.string "the TRAINER and {STR_VAR_1}.$"

gTVWorldOfMastersText02::
	.string "The master caught the day's last\n"
	.string "{STR_VAR_3} near {STR_VAR_2}.\p"
	.string "That POKéMON apparently enjoys\n"
	.string "a special status as a record holder.\p"
	.string "Skilled TRAINERS should be encouraged\n"
	.string "to challenge this fine record.\p"
	.string "That's all for today.\n"
	.string "Please tune in next time.$"

gTVTodaysRivalTrainerText00::
	.string "TODAY'S RIVAL TRAINER!\p"
	.string "Hello, fellow POKéMON TRAINERS!\n"
	.string "How are we all doing today?\p"
	.string "Today, like every other day,\n"
	.string "we'll examine one of our rivals!$"

gTVTodaysRivalTrainerText07::
	.string "Today's rival TRAINER is {STR_VAR_1},\n"
	.string "who's around {STR_VAR_3} now.\p"
	.string "{STR_VAR_1} has so far registered\n"
	.string "{STR_VAR_2} POKéMON in the POKéDEX.$"

gTVTodaysRivalTrainerText08::
	.string "Today's rival TRAINER is {STR_VAR_1},\n"
	.string "who's in a SECRET BASE now.\p"
	.string "{STR_VAR_1} has so far registered\n"
	.string "{STR_VAR_2} POKéMON in the POKéDEX.$"

gTVTodaysRivalTrainerText09::
	.string "Today's rival TRAINER is {STR_VAR_1}.\p"
	.string "So far, {STR_VAR_1} has registered\n"
	.string "{STR_VAR_2} POKéMON in the POKéDEX.$"

gTVTodaysRivalTrainerText10::
	.string "Today's rival TRAINER is {STR_VAR_1},\n"
	.string "who's on a ferry now.\p"
	.string "{STR_VAR_1} has so far registered\n"
	.string "{STR_VAR_2} POKéMON in the POKéDEX.$"

	.string "$"

gTVTodaysRivalTrainerText01::
	.string "And how many BADGES does our rival\n"
	.string "have? The number is {STR_VAR_1}!$"

gTVTodaysRivalTrainerText02::
	.string "But our rival hasn't obtained\n"
	.string "a single BADGE yet!$"

gTVTodaysRivalTrainerText03::
	.string "Our rival hasn't obtained a single\n"
	.string "BATTLE FRONTIER Symbol yet.$"

gTVTodaysRivalTrainerText04::
	.string "Let's see how many BATTLE FRONTIER\n"
	.string "Symbols our rival has.\p"
	.string "Gold Symbols: {STR_VAR_1}!\n"
	.string "Silver Symbols: {STR_VAR_2}!$"

gTVTodaysRivalTrainerText05::
	.string "Our rival has collected {STR_VAR_1} Battle\n"
	.string "Point(s) at the BATTLE FRONTIER.$"

gTVTodaysRivalTrainerText06::
	.string "So, how did you measure up in\n"
	.string "comparison to {STR_VAR_1}?\p"
	.string "The adventure rolls on!\p"
	.string "Fellow TRAINERS!\p"
	.string "Let's all keep moving forward\n"
	.string "and ahead of our rivals!$"

TrendWatcher_Text_Intro::
	.string "DEWFORD TREND-WATCHER NETWORK!\p"
	.string "MC: Wassup?\n"
	.string "We'll keep it real with the latest on\l"
	.string "what's hip and happening in DEWFORD.\p"
	.string "Our guest today is this old cat whose\n"
	.string "claim to fame is being the authority\l"
	.string "on all things in DEWFORD.\p"
	.string "Old man: Glad to be here.\p"
	.string "MC: Let's cut to the chase, right on.\p"
	.string "What's your word on what's groovin'\n"
	.string "the good folks of DEWFORD?\p"
	.string "Old man: {STR_VAR_1} {STR_VAR_2}.\p"
	.string "MC: {STR_VAR_1} {STR_VAR_2},\n"
	.string "you say?\p"
	.string "Old man: No.\p"
	.string "{STR_VAR_1} {STR_VAR_2} never\n"
	.string "did get popular at all.\p"
	.string "Would you like to hear about it?\p"
	.string "MC: Uh, no. What we want to know is\n"
	.string "what's the in thing of the moment…$"

@ Identical to below, may have been different in other languages
TrendWatcher_Text_MaleTaughtMePhrase::
	.string "Old man: {STR_VAR_1} {STR_VAR_2}\n"
	.string "was what {STR_VAR_3} from LITTLEROOT\l"
	.string "taught me as being trendy…$"

TrendWatcher_Text_FemaleTaughtMePhrase::
	.string "Old man: {STR_VAR_1} {STR_VAR_2}\n"
	.string "was what {STR_VAR_3} from LITTLEROOT\l"
	.string "taught me as being trendy…$"

TrendWatcher_Text_PhraseWasHopeless::
	.string "But it was utterly hopeless.\p"
	.string "{STR_VAR_1} {STR_VAR_2} festival!\p"
	.string "{STR_VAR_1} {STR_VAR_2} contest!\p"
	.string "I tried teaching everyone the best\n"
	.string "I could, but…\p"
	.string "Perhaps the {STR_VAR_1} part just\n"
	.string "wasn't right…\p"
	.string "MC: Uh, excuse me, compadre, I need\n"
	.string "to hear about what's in now…$"

@ Identical to below, may have been different in other languages
TrendWatcher_Text_MaleTellMeBigger::
	.string "Old man: {STR_VAR_3}!\n"
	.string "Please, tell me something bigger than\l"
	.string "that {STR_VAR_1} {STR_VAR_2}!$"

TrendWatcher_Text_FemaleTellMeBigger::
	.string "Old man: {STR_VAR_3}!\n"
	.string "Please, tell me something bigger than\l"
	.string "that {STR_VAR_1} {STR_VAR_2}!$"

TrendWatcher_Text_Outro::
	.string "MC: …Uh… So, there you have it,\n"
	.string "all you trendy, hep cats out there!\p"
	.string "{STR_VAR_1} {STR_VAR_2}…uh…\n"
	.string "Didn't get hip or happening in DEWFORD!\p"
	.string "My time is up. Catch you on the fly!\p"
	.string "Old man: {STR_VAR_1} {STR_VAR_2}!$"

gTVHoennTreasureInvestigatorsText00::
	.string "HOENN TREASURE INVESTIGATORS!\p"
	.string "Hi, gang!\n"
	.string "Score any secret items lately?\p"
	.string "As always, we'll examine eyewitness\n"
	.string "reports of secrets from all over!\p"
	.string "Let's start with a letter.\n"
	.string "It says, “{STR_VAR_1} discovered!”$"

gTVHoennTreasureInvestigatorsText01::
	.string "Wow, we'd better check this letter\n"
	.string "out! Let me read it to you.\p"
	.string "…Dear INVESTIGATORS,\n"
	.string "I hope you are well.\p"
	.string "I recently saw {STR_VAR_2} somewhere\n"
	.string "around {STR_VAR_3}.\p"
	.string "The TRAINER found the item\n"
	.string "{STR_VAR_1}. It made me envious.\p"
	.string "…Well, good going, {STR_VAR_2}!\p"
	.string "Viewers, let that motivate you to\n"
	.string "fire up your ITEMFINDERS and search!\p"
	.string "I'll be waiting for exciting news\n"
	.string "from all of you!$"

gTVHoennTreasureInvestigatorsText02::
	.string "Wow, we'd better check this letter\n"
	.string "out! Let me read it to you.\p"
	.string "…Dear INVESTIGATORS,\n"
	.string "I hope you are well.\p"
	.string "I recently saw {STR_VAR_2} on a ferry.\p"
	.string "The TRAINER found the item\n"
	.string "{STR_VAR_1}. It made me envious.\p"
	.string "…Well, good going, {STR_VAR_2}!\p"
	.string "Viewers, let that motivate you to\n"
	.string "fire up your ITEMFINDERS and search!\p"
	.string "I'll be waiting for exciting news\n"
	.string "from all of you!$"

gTVFindThatGamerText00::
	.string "FIND THAT GAMER!\p"
	.string "Hey, all you gamers!\n"
	.string "How's your {STR_VAR_2} spinning?\p"
	.string "Like always, we'll cast our spotlight\n"
	.string "on a rare TRAINER who's visited the\l"
	.string "GAME CORNER!\p"
	.string "Today, our no. 1 gamer is…\n"
	.string "{STR_VAR_1}!$"

gTVFindThatGamerText01::
	.string "{STR_VAR_1} played the {STR_VAR_2} game\n"
	.string "and won a rare {STR_VAR_3} COINS.\p"
	.string "“When {STR_VAR_1} comes, we need to\n"
	.string "make sure we have enough COINS.”\p"
	.string "That's what the GAME CORNER clerks\n"
	.string "mutter when our gamer is in play!\p"
	.string "Viewers, it's best to watch your COINS\n"
	.string "like {STR_VAR_1} if you visit the GAME\l"
	.string "CORNER and play the {STR_VAR_2} game.\p"
	.string "This is live from the GAME CORNER--\n"
	.string "where you can feel the excitement!\p"
	.string "That's all for today!$"

gTVFindThatGamerText02::
	.string "{STR_VAR_1} played the {STR_VAR_2} game\n"
	.string "and lost {STR_VAR_3} COINS.\p"
	.string "“When {STR_VAR_1} comes, our COIN\n"
	.string "sales seem to increase.”\p"
	.string "That's what the GAME CORNER clerks\n"
	.string "say when our gamer is in play!$"

gTVFindThatGamerText03::
	.string "Viewers, it's best to watch your COINS\n"
	.string "like {STR_VAR_1} if you visit the GAME\l"
	.string "CORNER and play the {STR_VAR_2} game.\p"
	.string "This is live from the GAME CORNER--\n"
	.string "where you can feel the excitement!\p"
	.string "That's all for today!$"

gTVBreakingNewsText00::
	.string "BREAKING NEWS TV!$"

gTVBreakingNewsText01::
	.string "Rare {STR_VAR_2} caught by\n"
	.string "{STR_VAR_1}!\p"
	.string "We're live from the vicinity of\n"
	.string "{STR_VAR_3}!\p"
	.string "{STR_VAR_1} successfully captured\n"
	.string "a rare {STR_VAR_2} earlier here!$"

gTVBreakingNewsText02::
	.string "When {STR_VAR_1} encountered the rare\n"
	.string "{STR_VAR_2}, the TRAINER sent out\l"
	.string "the POKéMON {STR_VAR_3}.$"

gTVBreakingNewsText03::
	.string "In the battle, the number of POKé\n"
	.string "BALLS thrown by the TRAINER was {STR_VAR_1}.\p"
	.string "Ultimately, the rare POKéMON was\n"
	.string "caught by the {STR_VAR_2} used last.$"

gTVBreakingNewsText04::
	.string "In that instant, {STR_VAR_2}\n"
	.string "echoed with {STR_VAR_1}'s roars of\l"
	.string "triumphant joy.\p"
	.string "I must say I'm a little envious of\n"
	.string "{STR_VAR_1}. I'd love to roar, too.\p"
	.string "…That ends the live feed from\n"
	.string "the happy scene!$"

gTVBreakingNewsText05::
	.string "{STR_VAR_1} fails to capture a rare\n"
	.string "{STR_VAR_2}!\p"
	.string "We're live from the vicinity of\n"
	.string "{STR_VAR_3}!\p"
	.string "It was here that {STR_VAR_1} failed\n"
	.string "to capture a rare {STR_VAR_2}!$"

gTVBreakingNewsText06::
	.string "When {STR_VAR_1} encountered the rare\n"
	.string "{STR_VAR_2}, the TRAINER sent out\l"
	.string "the POKéMON {STR_VAR_3}.$"

gTVBreakingNewsText07::
	.string "The TRAINER made the {STR_VAR_2}\n"
	.string "use the move {STR_VAR_1}.\p"
	.string "Without meaning to, the TRAINER\n"
	.string "made the rare POKéMON faint…$"

gTVBreakingNewsText12::
	.string "However, {STR_VAR_1} panicked at\n"
	.string "the sight of the rare {STR_VAR_2}.\p"
	.string "In confusion, the TRAINER ordered\n"
	.string "{STR_VAR_3} to attack.\p"
	.string "Without meaning to, the TRAINER\n"
	.string "made the rare POKéMON faint.$"

gTVBreakingNewsText08::
	.string "In that instant, {STR_VAR_2}\n"
	.string "echoed with {STR_VAR_1}'s shrieks of\l"
	.string "frustration…$"

gTVBreakingNewsText09::
	.string "However, {STR_VAR_1} seemed to run\n"
	.string "out of POKé BALLS.\p"
	.string "The TRAINER had to break off\n"
	.string "the battle with the rare {STR_VAR_2}.\p"
	.string "In that instant, {STR_VAR_3}\n"
	.string "echoed with {STR_VAR_1}'s shrieks of\l"
	.string "frustration…$"

gTVBreakingNewsText10::
	.string "However, the {STR_VAR_2} fled without\n"
	.string "warning.\p"
	.string "In that instant, {STR_VAR_3}\n"
	.string "echoed with {STR_VAR_1}'s shrieks of\l"
	.string "frustration…$"

gTVBreakingNewsText11::
	.string "I must say I feel for {STR_VAR_1}.\n"
	.string "Why, it makes me want to shriek, too.\p"
	.string "…That ends the live feed from\n"
	.string "the melancholy scene!$"

gTVPokemonLotteryWinnerFlashReportText00::
	.string "It's exciting!\n"
	.string "It's dramatic!\p"
	.string "It's the POKéMON LOTTERY\n"
	.string "WINNER FLASH REPORT!\p"
	.string "Hello! We're coming at you live from\n"
	.string "the POKéMON LOTTERY CORNER on\l"
	.string "the ground floor of the LILYCOVE\l"
	.string "DEPARTMENT STORE!\p"
	.string "Like it always happens, another\n"
	.string "lucky TRAINER appeared today!\p"
	.string "That TRAINER's name…\n"
	.string "{STR_VAR_1}!\p"
	.string "{STR_VAR_1} won the {STR_VAR_2} prize\n"
	.string "and took home the {STR_VAR_3}!\p"
	.string "{STR_VAR_1}!\n"
	.string "Congratulations!\p"
	.string "Viewers, don't just watch,\n"
	.string "get in on the action!\p"
	.string "All of us at the LILYCOVE DEPARTMENT\n"
	.string "STORE look forward to your next visit!\p"
	.string "This has been a live broadcast from\n"
	.string "the LILYCOVE DEPARTMENT STORE,\l"
	.string "offering you the greatest selection\l"
	.string "in all HOENN!$"

gTVThePokemonBattleSeminarText00::
	.string "THE POKéMON BATTLE SEMINAR!\p"
	.string "We examine battles to see what\n"
	.string "lessons we may learn from others.\p"
	.string "Today's case study is on {STR_VAR_1}'s\n"
	.string "battle.\p"
	.string "{STR_VAR_1}'s {STR_VAR_2} was\n"
	.string "battling one {STR_VAR_3}…$"

gTVThePokemonBattleSeminarText01::
	.string "And it used the move {STR_VAR_3}\n"
	.string "on the {STR_VAR_2}…\p"
	.string "Hmm… {STR_VAR_1}!\n"
	.string "That's the wrong thing to do!$"

gTVThePokemonBattleSeminarText02::
	.string "In addition to the doomed move,\n"
	.string "the TRAINER's {STR_VAR_1} also knew$"

gTVThePokemonBattleSeminarText03::
	.string "the moves {STR_VAR_1}, {STR_VAR_2},\n"
	.string "and {STR_VAR_3}.$"

gTVThePokemonBattleSeminarText04::
	.string "the moves {STR_VAR_1} and\n"
	.string "{STR_VAR_2}.$"

gTVThePokemonBattleSeminarText05::
	.string "the move {STR_VAR_2}.$"

gTVThePokemonBattleSeminarText06::
	.string "So, in this situation, what should\n"
	.string "the TRAINER have used?\p"
	.string "… … … … … …\n"
	.string "The move {STR_VAR_1}!\p"
	.string "The move {STR_VAR_1} would have been\n"
	.string "absolutely better than {STR_VAR_2}.\p"
	.string "Viewers, I urge you to learn from this\n"
	.string "case and battle with intelligence!\p"
	.string "Until next time, farewell!$"

gTVTrainerFanClubText00::
	.string "All together now!\n"
	.string "TRAINER FAN CLUB!\p"
	.string "MC: How's everyone groovin'?\n"
	.string "Today, we've rounded up the fans of\l"
	.string "the hyper-popular TRAINER {STR_VAR_1}!\p"
	.string "FANS: Wrooooooaaaaah!\p"
	.string "FANS: {STR_VAR_1}!\p"
	.string "MC: Everyone!\n"
	.string "How do you like {STR_VAR_1}?!\p"
	.string "FANS: We love {STR_VAR_1}!\p"
	.string "MC: What do you love about\n"
	.string "{STR_VAR_1}?!$"

gTVTrainerFanClubText01::
	.string "FANS: Their cool way of throwing\n"
	.string "POKé BALLS!$"

gTVTrainerFanClubText02::
	.string "FANS: Their adorable way of running!$"

gTVTrainerFanClubText03::
	.string "FANS: How the TRAINER turns tough\n"
	.string "when the going gets tough!$"

gTVTrainerFanClubText04::
	.string "FANS: The TRAINER's knowledge of\n"
	.string "POKéMON!$"

gTVTrainerFanClubText05::
	.string "FANS: The TRAINER's kindness toward\n"
	.string "all POKéMON!$"

gTVTrainerFanClubText06::
	.string "FANS: The TRAINER's amazing\n"
	.string "BIKE-riding techniques!$"

gTVTrainerFanClubText07::
	.string "FANS: The TRAINER's impressive\n"
	.string "item-buying style!$"

gTVTrainerFanClubText08::
	.string "FANS: The TRAINER's charming way\n"
	.string "of nicknaming POKéMON!$"

gTVTrainerFanClubText09::
	.string "FANS: The TRAINER's nifty style of\n"
	.string "decorating a SECRET BASE!$"

gTVTrainerFanClubText10::
	.string "FANS: The TRAINER's bold ways of\n"
	.string "using TMs!$"

gTVTrainerFanClubText11::
	.string "MC: As you've just seen, {STR_VAR_1}\n"
	.string "is hot! Like, too hot to touch, yow!\p"
	.string "Among {STR_VAR_1}'s FANS\n"
	.string "there's a special slogan!\p"
	.string "MC: When I say {STR_VAR_1},\n"
	.string "you say…\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!\p"
	.string "MC: That's right, when someone says,\n"
	.string "“{STR_VAR_1}”…\p"
	.string "Come back with, “{STR_VAR_2}\n"
	.string "{STR_VAR_3}!”\p"
	.string "That has such a unique ring to it!\n"
	.string "I can see why people become FANS\l"
	.string "of {STR_VAR_1}!\p"
	.string "Okay, you, in front of the TV, join us!\n"
	.string "All together now!\p"
	.string "MC: When I say {STR_VAR_1},\n"
	.string "you say…\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!\p"
	.string "MC: Thanks for joining us, all you\n"
	.string "wild FANS of {STR_VAR_1}!\l"
	.string "That's the show! See you again!\p"
	.string "MC: When I say {STR_VAR_1},\n"
	.string "you say…\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!$"

TVSpotTheCuties_Text_Intro::
	.string "SPOT THE CUTIES!\n"
	.string "POKéMON IN RIBBONS!\p"
	.string "Hello, my sweet viewers!\p"
	.string "I just know you'll agree, but a POKéMON\n"
	.string "wearing RIBBONS is simply divine!\p"
	.string "Today, I want to share with you\n"
	.string "a lovely POKéMON I spotted while\l"
	.string "out on a stroll in town.\p"
	.string "Today's featured pretty POKéMON\n"
	.string "is {STR_VAR_1}'s {STR_VAR_2}.$"

TVSpotTheCuties_Text_RibbonsLow::
	.string "The number of RIBBONS that\n"
	.string "{STR_VAR_2} wears is {STR_VAR_3}.\p"
	.string "It says a lot about how much\n"
	.string "{STR_VAR_1} adores the POKéMON.$"

TVSpotTheCuties_Text_RibbonsMid::
	.string "{STR_VAR_2} wears an amazing\n"
	.string "{STR_VAR_3} RIBBONS!\p"
	.string "It speaks volumes about {STR_VAR_1}'s\n"
	.string "commitment to the POKéMON!$"

TVSpotTheCuties_Text_RibbonsHigh::
	.string "{STR_VAR_2} wears an incredible\n"
	.string "{STR_VAR_3} RIBBONS!\p"
	.string "It shows you {STR_VAR_1}'s total\n"
	.string "dedication as a collector!$"

TVSpotTheCuties_Text_RibbonIntro::
	.string "Let us take a closer look at the many\n"
	.string "RIBBONS worn by {STR_VAR_2}.$"

TVSpotTheCuties_Text_RibbonChampion::
	.string "The CHAMPION RIBBON is especially\n"
	.string "fetching.\p"
	.string "{STR_VAR_2} received it upon entering\n"
	.string "the HALL OF FAME.\p"
	.string "It verily draws out the bravery\n"
	.string "of {STR_VAR_2}.\p"
	.string "{STR_VAR_2} and the CHAMP RIBBON!\n"
	.string "The combination is super effective!$"

TVSpotTheCuties_Text_RibbonWinning::
	.string "The WINNING RIBBON is especially\n"
	.string "fetching.\p"
	.string "{STR_VAR_2} received it for its feats\n"
	.string "at the BATTLE TOWER.\p"
	.string "It verily draws out the mightiness\n"
	.string "of {STR_VAR_2}.\p"
	.string "{STR_VAR_2} and the WINNING RIBBON!\n"
	.string "The combination is super effective!$"

TVSpotTheCuties_Text_RibbonVictory::
	.string "The VICTORY RIBBON is especially\n"
	.string "fetching.\p"
	.string "{STR_VAR_2} received it for its feats\n"
	.string "at the BATTLE TOWER.\p"
	.string "It verily draws out the incredible\n"
	.string "mightiness of {STR_VAR_2}.\p"
	.string "{STR_VAR_2} and the VICTORY RIBBON!\n"
	.string "The combination is super effective!$"

TVSpotTheCuties_Text_RibbonArtist::
	.string "The ARTIST RIBBON is especially\n"
	.string "fetching.\p"
	.string "{STR_VAR_2} received it for being\n"
	.string "the model for an artist.\p"
	.string "It verily draws out the pop-star charm\n"
	.string "of {STR_VAR_2}.\p"
	.string "{STR_VAR_2} and the ARTIST RIBBON!\n"
	.string "The combination is super effective!$"

TVSpotTheCuties_Text_RibbonEffort::
	.string "The Hard Worker RIBBON is\n"
	.string "especially fetching.\p"
	.string "{STR_VAR_2} received it for being\n"
	.string "an especially dedicated worker.\p"
	.string "It verily draws out the determination\n"
	.string "of {STR_VAR_2}.\p"
	.string "{STR_VAR_2} and the Hard Worker RIBBON!\n"
	.string "The combination is super effective!$"

TVSpotTheCuties_Text_Outro::
	.string "…Sigh…\p"
	.string "RIBBONS and POKéMON…\n"
	.string "They go so wonderfully together!\p"
	.string "Before I swoon,\n"
	.string "I bid you all farewell!$"

gTVPokemonNewsBattleFrontierText00::
	.string "Greetings!\n"
	.string "It's time for POKéMON NEWS.\p"
	.string "We've got some uplifting news from\n"
	.string "the BATTLE FRONTIER.$"

gTVPokemonNewsBattleFrontierText01::
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "{STR_VAR_2}-win-streak record while on\l"
	.string "the BATTLE TOWER's SINGLE BATTLE\l"
	.string "ROOM challenge.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText02::
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "{STR_VAR_2}-win-streak record while on\l"
	.string "the BATTLE TOWER's DOUBLE BATTLE\l"
	.string "ROOM challenge.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText03::
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "{STR_VAR_2}-win-streak record while on\l"
	.string "the BATTLE TOWER's MULTI BATTLE\l"
	.string "ROOM challenge.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText04::
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "{STR_VAR_2}-win-streak record while on\l"
	.string "the BATTLE TOWER's LINK MULTI BATTLE\l"
	.string "ROOM challenge.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText05::
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "{STR_VAR_2}-championship-streak record\l"
	.string "competing in the BATTLE DOME's\l"
	.string "SINGLE BATTLE Tournaments.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText06::
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "{STR_VAR_2}-championship-streak record\l"
	.string "competing in the BATTLE DOME's\l"
	.string "DOUBLE BATTLE Tournaments.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText07::
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "{STR_VAR_2}-win-streak record while on\l"
	.string "the BATTLE FACTORY's Battle\l"
	.string "Swap Single challenge.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText08::
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "{STR_VAR_2}-win-streak record while on\l"
	.string "the BATTLE FACTORY's Battle\l"
	.string "Swap Double challenge.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText09::
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "record of clearing {STR_VAR_2} rooms\l"
	.string "while on the BATTLE PIKE's Battle\l"
	.string "Choice challenge.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText10::
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "{STR_VAR_2}-win-streak record while\l"
	.string "competing in the BATTLE ARENA's\l"
	.string "Set KO Tournaments.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText11::
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "{STR_VAR_2}-win-streak record while on\l"
	.string "the BATTLE PALACE's SINGLE BATTLE\l"
	.string "HALL challenge.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText12::
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "{STR_VAR_2}-win-streak record while on\l"
	.string "the BATTLE PALACE's DOUBLE BATTLE\l"
	.string "HALL challenge.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText13::
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "record of clearing {STR_VAR_2} floors\l"
	.string "while on the BATTLE PYRAMID's\l"
	.string "Battle Quest challenge.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText14::
	.string "And to the three POKéMON, {STR_VAR_1},\n"
	.string "{STR_VAR_2}, and {STR_VAR_3}!\p"
	.string "Congratulations for your\n"
	.string "record-breaking performance!$"

gTVPokemonNewsBattleFrontierText15::
	.string "And to the two POKéMON, {STR_VAR_1}\n"
	.string "and {STR_VAR_2}!\p"
	.string "Congratulations for your\n"
	.string "record-breaking performance!$"

gTVPokemonNewsBattleFrontierText16::
	.string "And to the four POKéMON: {STR_VAR_1}!\p"
	.string "{STR_VAR_2}!\p"
	.string "{STR_VAR_3}!$"

gTVPokemonNewsBattleFrontierText17::
	.string "And {STR_VAR_1}!\p"
	.string "Congratulations for your\n"
	.string "record-breaking performance!$"

gTVPokemonNewsBattleFrontierText18::
	.string "Let's hope for more record-setting\n"
	.string "feats from {STR_VAR_1} and the loyal\l"
	.string "POKéMON!\p"
	.string "That's the news on POKéMON NEWS!$"

gTVWhatsNo1InHoennTodayText00::
	.string "WHAT'S NO. 1 IN HOENN TODAY?\n"
	.string "Yes, it's that time again!\p"
	.string "Hello, viewers! Are you giving your\n"
	.string "best at whatever you do?\p"
	.string "Let's have a look at the TRAINER\n"
	.string "who did the very best today!\p"
	.string "Today's no. 1 TRAINER is none other\n"
	.string "than {STR_VAR_1}!$"

gTVWhatsNo1InHoennTodayText01::
	.string "In one day, {STR_VAR_1} spun the SLOTS\n"
	.string "at the GAME CORNER {STR_VAR_2} times.\p"
	.string "While playing, {STR_VAR_1} was heard\n"
	.string "murmuring, “For me, the reels don't\l"
	.string "even move…”\l"
	.string "Isn't that interesting?$"

gTVWhatsNo1InHoennTodayText02::
	.string "In one day, {STR_VAR_1} played\n"
	.string "the ROULETTE game at the GAME\l"
	.string "CORNER {STR_VAR_2} times.\p"
	.string "While playing, {STR_VAR_1} shouted,\n"
	.string "“Let the balls decide!”\p"
	.string "The TRAINER's eyes were focused and\n"
	.string "the face showed concentration.$"

gTVWhatsNo1InHoennTodayText03::
	.string "In one day, {STR_VAR_1} battled\n"
	.string "wild POKéMON {STR_VAR_2} times!\p"
	.string "Apparently, {STR_VAR_1}'s POKéMON\n"
	.string "have grown incomparably stronger.\p"
	.string "They appear eager to battle anywhere,\n"
	.string "anytime, and anyhow!$"

gTVWhatsNo1InHoennTodayText04::
	.string "In just one day, {STR_VAR_1} spun\n"
	.string "the BERRY BLENDER {STR_VAR_2} times!\p"
	.string "Toward the end, even {STR_VAR_1}\n"
	.string "seemed to get dizzy.\p"
	.string "The TRAINER appeared to totter\n"
	.string "around like a SPINDA!$"

gTVWhatsNo1InHoennTodayText05::
	.string "In just one day, {STR_VAR_1} planted\n"
	.string "{STR_VAR_2} BERRIES!\p"
	.string "As a result, {STR_VAR_1}'s clothes\n"
	.string "became filthy with dirt.\p"
	.string "Where the TRAINER planted, countless\n"
	.string "flowers have burst into bloom.\p"
	.string "The flowers are said to soothe\n"
	.string "the emotions of people.$"

gTVWhatsNo1InHoennTodayText06::
	.string "In just one day, {STR_VAR_1} picked\n"
	.string "{STR_VAR_2} BERRIES!\p"
	.string "{STR_VAR_1}'s BAG became so filled\n"
	.string "with BERRIES, the TRAINER had trouble\l"
	.string "walking afterward!$"

gTVWhatsNo1InHoennTodayText07::
	.string "In just one day, {STR_VAR_1} obtained\n"
	.string "{STR_VAR_2} Battle Points!\p"
	.string "{STR_VAR_1} was later seen wrestling\n"
	.string "with the choice of exchanging\l"
	.string "the Battle Points for a cool item or\l"
	.string "a nifty interior decoration.\p"
	.string "The TRAINER reportedly was grinning\n"
	.string "while mulling options.$"

gTVWhatsNo1InHoennTodayText08::
	.string "Well, isn't that something!\p"
	.string "{STR_VAR_1}!\n"
	.string "You're today's no. 1 TRAINER!\p"
	.string "Viewers, take heart from {STR_VAR_1}!\n"
	.string "You, too, can be no. 1 every day!$"

gTVSafariFanClubText00::
	.string "SAFARI FAN CLUB!\p"
	.string "REPORTER: All right, mates!\n"
	.string "Tossing them SAFARI BALLS, are you?\p"
	.string "You can bet I am here in the SAFARI\n"
	.string "ZONE chock-full of amazing POKéMON!\p"
	.string "Let's get with it and have a chat with\n"
	.string "this good fellow of a SAFARI GUIDE!\p"
	.string "All right, mate, how are the visiting\n"
	.string "TRAINERS looking?$"

gTVSafariFanClubText01::
	.string "GUIDE: Everyone seems to be going\n"
	.string "hard at it.\p"
	.string "{STR_VAR_1} is doing especially well.\p"
	.string "Why, before, {STR_VAR_1} caught\n"
	.string "{STR_VAR_2} POKéMON.$"

gTVSafariFanClubText02::
	.string "The TRAINER is clever with {POKEBLOCK}S.\n"
	.string "Used {STR_VAR_2} that time, I think.$"

gTVSafariFanClubText03::
	.string "The TRAINER didn't use a single\n"
	.string "{POKEBLOCK}! Not a one!\p"
	.string "There's an expert for you.$"

gTVSafariFanClubText04::
	.string "REPORTER: Is that right, then?\p"
	.string "Sounds like our mate {STR_VAR_1}\n"
	.string "is a stout SAFARI master!\p"
	.string "GUIDE: I hope the TRAINER comes back\n"
	.string "and shows us that great technique.$"

gTVSafariFanClubText05::
	.string "GUIDE: No one seems to be doing\n"
	.string "very well.\p"
	.string "{STR_VAR_1} had it especially bad.\p"
	.string "Why, before, the TRAINER only\n"
	.string "managed to catch {STR_VAR_2} POKéMON.$"

gTVSafariFanClubText06::
	.string "GUIDE: No one seems to be doing\n"
	.string "very well.\p"
	.string "{STR_VAR_1} had it especially bad.\p"
	.string "Why, before, the TRAINER didn't\n"
	.string "catch one POKéMON. Not a one!$"

gTVSafariFanClubText07::
	.string "The TRAINER does use {POKEBLOCK}S.\n"
	.string "Used {STR_VAR_2} that time, I think.\p"
	.string "But, boy, I wish the TRAINER would\n"
	.string "get a bit better at this.$"

gTVSafariFanClubText08::
	.string "I think the TRAINER would have better\n"
	.string "luck using {POKEBLOCK}S, which weren't\l"
	.string "used at all that time.$"

gTVSafariFanClubText09::
	.string "REPORTER: Is that right, then?\p"
	.string "Sounds like our mate {STR_VAR_1}\n"
	.string "needs more SAFARI seasoning.\p"
	.string "GUIDE: I hope the TRAINER visits\n"
	.string "over and over to get the hang of it.$"

gTVSafariFanClubText10::
	.string "REPORTER: Quite right, it is!\n"
	.string "Facing up to challenges is important!\p"
	.string "Viewers, come on down to the SAFARI\n"
	.string "and make the challenge yourself!\p"
	.string "Until next time, cheerio!$"

gTVPokemonBattleUpdateText00:: @ 0828ABCC
	.string "“POKéMON BATTLE UPDATE!”\p"
	.string "Bringing you the results of POKéMON\n"
	.string "battles as they come in!$"

gTVPokemonBattleUpdateText01::
	.string "The TRAINERS {STR_VAR_1} and\n"
	.string "{STR_VAR_2} faced each other in\l"
	.string "a {STR_VAR_3} BATTLE.\p"
	.string "This match ended in victory for\n"
	.string "{STR_VAR_1}!$"

gTVPokemonBattleUpdateText02::
	.string "In the battle, {STR_VAR_1}'s\n"
	.string "{STR_VAR_2} was a formidable force\l"
	.string "using {STR_VAR_3}!$"

gTVPokemonBattleUpdateText03::
	.string "{STR_VAR_1}'s {STR_VAR_2} had a weak\n"
	.string "showing that really hurt.$"

gTVPokemonBattleUpdateText04::
	.string "Congratulations on your victory,\n"
	.string "{STR_VAR_1}!\p"
	.string "And for the defeated {STR_VAR_2},\n"
	.string "we hope for a better result next time!\p"
	.string "This concludes this episode of\n"
	.string "“POKéMON BATTLE UPDATE!”$"

gTVPokemonBattleUpdateText05::
	.string "The teams of TRAINERS {STR_VAR_1} and\n"
	.string "{STR_VAR_2} met in a MULTI BATTLE.\p"
	.string "This match ended in victory for\n"
	.string "{STR_VAR_1}'s team.$"

gTVPokemonBattleUpdateText06::
	.string "In the battle, the {STR_VAR_2} on\n"
	.string "{STR_VAR_1}'s team was a formidable\l"
	.string "force using {STR_VAR_3}.$"

gTVPokemonBattleUpdateText07::
	.string "The weak showing by the {STR_VAR_3}\n"
	.string "on {STR_VAR_2}'s team really hurt.\p"
	.string "Congratulations on your team's\n"
	.string "victory, {STR_VAR_1}!\p"
	.string "As for the defeated {STR_VAR_2}'s team,\n"
	.string "we hope for a better result next time!\p"
	.string "This concludes this episode of\n"
	.string "“POKéMON BATTLE UPDATE!”$"

GabbyAndTy_Text_GabbyPreFirstBattle:
	.string "GABBY: Oh! We've just spotted a tough-\n"
	.string "looking TRAINER here of all places!\p"
	.string "Okay, roll camera!\n"
	.string "Let's get this interview.$"

GabbyAndTy_Text_GabbyIntro:
	.string "GABBY: Oh! You're {PLAYER}! Hi!\n"
	.string "Do you remember us from last time?\p"
	.string "Can you show us how much stronger\n"
	.string "you've become? Okay, cue interview!$"

GabbyAndTy_Text_GabbyDefeatFirstTime:
	.string "GABBY: My eyes didn't lie!\n"
	.string "I did discover an astonishing TRAINER!$"

GabbyAndTy_Text_WhoAreYouInterview:
	.string "GABBY: Awesome! Awesome!\n"
	.string "Who are you?!\p"
	.string "I knew we were onto something wild\n"
	.string "when we spotted you!\p"
	.string "Oh, please let me explain. We travel\n"
	.string "around everywhere interviewing all\l"
	.string "sorts of TRAINERS.\p"
	.string "So, would you give us a bit of your time\n"
	.string "for an interview?$"

GabbyAndTy_Text_QuoteFromLastInterview:
	.string "GABBY: “{STR_VAR_1}!”\p"
	.string "Remember? That's the quote you gave\n"
	.string "us as the battle clincher last time.\p"
	.string "I never, ever forget stuff like that!$"

GabbyAndTy_Text_YouStompedUsInterviewAgain:
	.string "The last time we battled, you stomped\n"
	.string "us before we could brace ourselves…\p"
	.string "Anyway, what do you think?\n"
	.string "Do you want to be interviewed again?$"

GabbyAndTy_Text_YouThrewABallAtUsInterviewAgain:
	.string "The last time we battled, didn't you\n"
	.string "throw a POKé BALL at us?\p"
	.string "We were shocked! So we told everyone,\n"
	.string "just everyone, about it!\p"
	.string "Anyway, what do you think?\n"
	.string "Do you want to be interviewed again?$"

GabbyAndTy_Text_CleverItemSkillsInterviewAgain:
	.string "The last time we battled, your item\n"
	.string "skills cleverly did us in.\p"
	.string "Anyway, what do you think?\n"
	.string "Do you want to be interviewed again?$"

GabbyAndTy_Text_WeLookedRespectableInterviewAgain:
	.string "The last time we battled, we managed\n"
	.string "to look respectable.\p"
	.string "Anyway, what do you think?\n"
	.string "Do you want to be interviewed again?$"

GabbyAndTy_Text_InterviewAgain:
	.string "Anyway, what do you think?\n"
	.string "Do you want to be interviewed again?$"

GabbyAndTy_Text_DescribeYourFeelings:
	.string "You will?\n"
	.string "Thank you!\p"
	.string "Okay, I need you to describe your\n"
	.string "feelings about our battle, but it\l"
	.string "has to be short and sweet. Go!$"

GabbyAndTy_Text_PerfectWellBeSeeingYou:
	.string "GABBY: Mmm, yeah!\n"
	.string "That's the perfect clincher!\p"
	.string "I get the feeling that this will make\n"
	.string "a great TV show.\p"
	.string "There's a chance that they'll air this\n"
	.string "on TV, so make sure to look for us!\p"
	.string "Okay!\n"
	.string "We'll be seeing you!$"

GabbyAndTy_Text_DontGiveUpKeepingEyeOut:
	.string "GABBY: Oh…\p"
	.string "Okay, but don't give up!\n"
	.string "We'll be keeping an eye out for you!$"

GabbyAndTy_Text_KeepingAnEyeOutForYou:
	.string "GABBY: We'll be keeping an eye out\n"
	.string "for you!$"

GabbyAndTy_Text_GabbyNotEnoughMons:
	.string "GABBY: Is there a strong TRAINER\n"
	.string "anywhere with a lot of POKéMON?$"

GabbyAndTy_Text_GiveUsAnInterviewThisTime:
	.string "GABBY: Wow, you are something!\p"
	.string "You've gotten a lot stronger--a lot--\n"
	.string "since we last battled.\p"
	.string "We were right about you when we\n"
	.string "spotted you as a hot TRAINER.\p"
	.string "So, anyway, what do you think?\n"
	.string "Are you willing to give us an interview\l"
	.string "this time?$"

GabbyAndTy_Text_GabbyDefeat:
	.string "GABBY: That was an intense battle!\n"
	.string "Did you get all that on camera?$"

GabbyAndTy_Text_TyPreFirstBattle:
	.string "TY: Hey, lookie here! A tough-looking\n"
	.string "TRAINER here, of all places!\l"
	.string "Camera's rolling!$"

GabbyAndTy_Text_TyIntro:
	.string "TY: Hey, lookie here!\n"
	.string "I remember you!\p"
	.string "I'll get this battle all on this\n"
	.string "here camera!$"

GabbyAndTy_Text_TyPostBattle:
	.string "TY: You're a natural!\n"
	.string "Got me some prime footage right here!$"

GabbyAndTy_Text_TyNotEnoughMons:
	.string "TY: Do you only have the one POKéMON\n"
	.string "and that's it?\p"
	.string "If you had more POKéMON, it'd make for\n"
	.string "better footage, but…$"

GabbyAndTy_Text_TyDefeatFirstTime:
	.string "TY: Yep, we sure spotted a hot TRAINER.\n"
	.string "This is a huge scoop for us!$"

GabbyAndTy_Text_TyDefeat:
	.string "TY: Yep, I got it all.\n"
	.string "That whole battle's on camera.$"

gTVInSearchOfTrainersText00::
	.string "IN SEARCH OF TRAINERS…\p"
	.string "GABBY: Hi! Today I'm visiting an area\n"
	.string "near {STR_VAR_1}.\p"
	.string "We're trying to spot some up-and-\n"
	.string "coming new talent in the field.\p"
	.string "Today, we turned our lens on the\n"
	.string "TRAINER {PLAYER}.\p"
	.string "There's something about this TRAINER\n"
	.string "that piqued our interest.$"

gTVInSearchOfTrainersText01::
	.string "We've battled {PLAYER} before, but we\n"
	.string "can attest that the TRAINER has most\l"
	.string "definitely improved from before.\p"
	.string "I knew we were onto someone special\n"
	.string "when we spotted this TRAINER!$"

gTVInSearchOfTrainersText02::
	.string "The best way to determine how strong\n"
	.string "a TRAINER is…\p"
	.string "Well, the fastest way is to battle.\n"
	.string "And so we began our investigation!\p"
	.string "… …\p"
	.string "That's how we ended up in battle\n"
	.string "with {PLAYER}.\p"
	.string "In a dominating performance, we were\n"
	.string "flattened, rolled up, and tossed aside!\p"
	.string "{PLAYER} is ruthlessly strong…\p"
	.string "Here's our impressions after having\n"
	.string "battled our featured TRAINER.$"

gTVInSearchOfTrainersText03::
	.string "The combination of {STR_VAR_1} and\n"
	.string "{STR_VAR_3} was divine!\p"
	.string "The sight of them--{STR_VAR_1} and\n"
	.string "{STR_VAR_3}--selflessly supporting\l"
	.string "each other in the thick of battle…\p"
	.string "It was a marvelous sight to behold!\p"
	.string "{STR_VAR_2} was the move the TRAINER\n"
	.string "used last in our battle.\p"
	.string "The move {STR_VAR_2} is {STR_VAR_1}\n"
	.string "and {STR_VAR_3}'s sign of friendship!$"

gTVInSearchOfTrainersText04::
	.string "…I lost confidence in myself as\n"
	.string "a result of our encounter.\p"
	.string "We were beaten before we could launch\n"
	.string "a single attack.\l"
	.string "Ohhh… Snivel…\p"
	.string "In spite of that, {PLAYER}'s battles\n"
	.string "are worth seeing.\p"
	.string "I recommend confident TRAINERS to\n"
	.string "challenge {PLAYER}.$"

gTVInSearchOfTrainersText05::
	.string "There's only one thing to be said.\n"
	.string "Don't you dare throw a POKé BALL during\l"
	.string "a TRAINER battle!\p"
	.string "{PLAYER} is certainly strong, but has\n"
	.string "no clue about the basic rules.\p"
	.string "To our TV audience, I have a request.\p"
	.string "If you see {PLAYER}, please caution\n"
	.string "the TRAINER!$"

gTVInSearchOfTrainersText06::
	.string "{PLAYER} is adept at reading the\n"
	.string "opponent's actions.\p"
	.string "The timing of item usage was remarkably\n"
	.string "effective!$"

gTVInSearchOfTrainersText07::
	.string "Honestly speaking, I thought that\n"
	.string "I might even be pretty good.\p"
	.string "While we did end up losing, we did have\n"
	.string "a hotly contested battle.\p"
	.string "But if you're struggling against me,\n"
	.string "you have a ways to go, {PLAYER}!$"

gTVInSearchOfTrainersText08::
	.string "After our battle, we asked {PLAYER} for\n"
	.string "a succinct summary.\p"
	.string "The TRAINER replied, “{STR_VAR_1}.”\p"
	.string "{PLAYER}'s POKéMON {STR_VAR_2} and\n"
	.string "{STR_VAR_3}…\l"
	.string "And “{STR_VAR_1}”…\p"
	.string "Mmm! That's deep! There's deep\n"
	.string "significance behind that quote!\p"
	.string "It's no surprise--a good TRAINER has\n"
	.string "good things to say.\p"
	.string "That's all for today!\n"
	.string "See you again on our next broadcast!$"
